name: 'Run EE Server in a Docker container'
description: 'Run EE server. Returns once server is ready. Only tested on Linux and macOS'
# NOTE: do not share this server container with others
# since it's using the default admin / admin credentials
inputs:
  # All inputs in composite actions are strings
  oidc-provider-name:
    description: For pulling server images from JFrog
    required: true
  oidc-audience:
    description: For pulling server images from JFrog
    required: true
  features-content:
    description: For enabling strong consistency
    required: true
  server-tag:
    required: true
    description: Specify Docker tag
    default: 'latest'
  where-is-client-connecting-from:
    required: false
    description: 'docker-host, separate-docker-container, "remote-connection" via DOCKER_HOST'
    default: 'docker-host'

runs:
  using: "composite"
  steps:
  # Start up server
  - uses: aerospike/shared-workflows/.github/actions/setup-aerospike-server@48edf9ff59ab4da5f15915b22d8895f19ce7fd55
    id: setup-as-server
    with:
      enable-security: "true"
      enable-tls: "true"
      enable-strong-consistency: "true"
      features-content: ${{ inputs.features-content }}
      num-nodes: 1
      oidc-provider: ${{ inputs.oidc-provider-name }}
      oidc-audience: ${{ inputs.oidc-audience }}
      server-tag: ${{ inputs.server-tag }}
      env-vars: DEFAULT_TTL=2592000

  - run: echo SUPERUSER_NAME_AND_PASSWORD="superuser" >> $GITHUB_ENV
    shell: bash

  - run: |
      docker run --rm --network host aerospike/aerospike-tools asadm -U admin -P admin --enable --execute "manage acl \
          create user $SUPERUSER_NAME_AND_PASSWORD password $SUPERUSER_NAME_AND_PASSWORD \
          roles read-write-udf, sys-admin, user-admin, data-admin"
    shell: bash

  - name: Install crudini to manipulate config.conf
    run: pipx install crudini --pip-args "-c ${{ github.workspace }}/.github/workflows/requirements.txt"
    working-directory: .github/workflows
    shell: bash

  - name: Create config.conf
    run: cp config.conf.template config.conf
    working-directory: test
    shell: bash

  - name: Disable community edition connection
    run: crudini --existing=param --set config.conf community-edition hosts ''
    working-directory: test
    shell: bash

  - name: Set credentials in config file
    run: |
      crudini --existing=param --set config.conf enterprise-edition user ${{ env.SUPERUSER_NAME_AND_PASSWORD }}
      crudini --existing=param --set config.conf enterprise-edition password ${{ env.SUPERUSER_NAME_AND_PASSWORD }}
      crudini --set config.conf tls enable true
      # Cannot use abs path because config.conf is copied into Docker container during cibuildwheel tests
      crudini --set config.conf tls cafile ${{ steps.setup-as-server.outputs.tls-cert-dir }}/ca.crt
      crudini --set config.conf tls keyfile ${{ steps.setup-as-server.outputs.tls-cert-dir }}/client.key
      crudini --set config.conf tls certfile ${{ steps.setup-as-server.outputs.tls-cert-dir }}/client.crt
    working-directory: test
    shell: bash

  - name: Set IP address to localhost
    if: ${{ inputs.where-is-client-connecting-from == 'docker-host' }}
    run: echo SERVER_IP=127.0.0.1 >> $GITHUB_ENV
    working-directory: test
    shell: bash

  - name: Set IP address to remote machine running the Docker daemon
    if: ${{ inputs.where-is-client-connecting-from == 'remote-connection' }}
    run: |
      SERVER_IP=${DOCKER_HOST/tcp:\/\//}
      echo SERVER_IP=${SERVER_IP/:2375/} >> $GITHUB_ENV
    working-directory: test
    shell: bash

  - name: Set IP address to Docker container for the server
    if: ${{ inputs.where-is-client-connecting-from == 'separate-docker-container' }}
    run: |
      server_container_network_name=${{ steps.setup-as-server.outputs.network-name }}
      docker_query="{{ .NetworkSettings.Networks.$server_container_network_name.IPAddress }}"
      echo SERVER_IP=$(docker container inspect -f "$docker_query" ${{ steps.setup-as-server.outputs.container-names }}) >> $GITHUB_ENV
    shell: bash

  - name: Invalid input
    if: ${{ env.SERVER_IP == '' }}
    run: exit 1
    shell: bash

  # Here we just assume that TLS is enabled. Whenever the dev tests are run with run-ee-server.yml, TLS is enabled anyways.
  # TODO: but this needs to be fixed eventually for other clients that disable TLS for their tests.
  - name: Set EE server's IP address and TLS name for test config
    run: |
      cluster_name=$(docker run --rm --network host aerospike/aerospike-tools asinfo -U admin -P admin -v "get-config:context=service" -l | grep -i cluster-name | cut -d = -f 2)
      crudini --existing=param --set config.conf enterprise-edition hosts "${{ env.SERVER_IP }}:${{ steps.setup-as-server.outputs.tls-service-ports }}|${cluster_name}"
    working-directory: test
    shell: bash
