name: 'Run EE Server in a Docker container'
description: 'Run EE server. Returns once server is ready. Only tested on Linux and macOS'
# NOTE: do not share this server container with others
# since it's using the default admin / admin credentials
inputs:
  # All inputs in composite actions are strings
  registry-name:
    description: Registry name
    required: false
    default: docker.io
  registry-username:
    description: Required for using release candidates
    required: false
  # Github Composite Actions can't access secrets
  # so we need to pass them in as inputs
  registry-password:
    description: Required for using release candidates
    required: false
  image-name:
    required: false
    description: aerospike/aerospike-server-enterprise
    default: 'aerospike/aerospike-server-enterprise'
  server-tag:
    required: true
    description: Specify Docker tag
    default: 'latest'
  where-is-client-connecting-from:
    required: false
    description: 'docker-host, separate-docker-container, "remote-connection" via DOCKER_HOST'
    default: 'docker-host'
  env-vars:
    required: false
    description: Used to disable server features
    default: ''
outputs:
  container-name:
    description: 'Server container name'
    value: ${{ steps.get-container-name.outputs.container-name }}

runs:
  using: "composite"
  steps:
  # Start up server

  - name: Log into registry to get non-public server RCs
    # We can still pull public images while logged in, so just do this all the time to make things simple
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry-name }}
      username: ${{ inputs.registry-username }}
      password: ${{ inputs.registry-password }}

  - run: echo IMAGE_FULL_NAME=${{ inputs.registry-name }}/${{ inputs.image-name }}:${{ inputs.server-tag }} >> $GITHUB_ENV
    shell: bash

  - run: echo CA_CERT_FILE_NAME="ca.cer" >> $GITHUB_ENV
    shell: bash

  - run: echo TLS_PORT="4333" >> $GITHUB_ENV
    shell: bash

  # Input env vars will override the env vars we defined in this step
  - run: ${{ inputs.env-vars }} ./run-ee-server.bash
    working-directory: .github/workflows/docker-setup
    shell: bash
    env:
      STRONG_CONSISTENCY: 1
      SECURITY: 1
      MUTUAL_TLS: 1

  - id: get-container-name
    run: echo container-name=aerospike >> $GITHUB_OUTPUT
    working-directory: .github/workflows/docker-build-context
    shell: bash

  # Configure tests

  - name: Install crudini to manipulate config.conf
    run: pipx install crudini --pip-args "-c ${{ github.workspace }}/.github/workflows/requirements.txt"
    working-directory: .github/workflows
    shell: bash

  - name: Create config.conf
    run: cp config.conf.template config.conf
    working-directory: test
    shell: bash

  - name: Disable community edition connection
    run: crudini --existing=param --set config.conf community-edition hosts ''
    working-directory: test
    shell: bash

  - run: echo SUPERUSER_NAME_AND_PASSWORD="superuser" >> $GITHUB_ENV
    shell: bash

  - name: Set credentials in config file
    run: |
      crudini --existing=param --set config.conf enterprise-edition user ${{ env.SUPERUSER_NAME_AND_PASSWORD }}
      crudini --existing=param --set config.conf enterprise-edition password ${{ env.SUPERUSER_NAME_AND_PASSWORD }}
      crudini --set config.conf tls enable true
      # Cannot use abs path because config.conf is copied into Docker container during cibuildwheel tests
      crudini --set config.conf tls cafile ../.github/workflows/docker-setup/${{ env.CA_CERT_FILE_NAME }}
      crudini --set config.conf tls keyfile ../.github/workflows/docker-setup/client.pem
      crudini --set config.conf tls certfile ../.github/workflows/docker-setup/client.cer

    working-directory: test
    shell: bash

  - name: Set IP address to localhost
    if: ${{ inputs.where-is-client-connecting-from == 'docker-host' }}
    run: echo SERVER_IP=127.0.0.1 >> $GITHUB_ENV
    working-directory: test
    shell: bash

  - name: Set IP address to remote machine running the Docker daemon
    if: ${{ inputs.where-is-client-connecting-from == 'remote-connection' }}
    run: |
      SERVER_IP=${DOCKER_HOST/tcp:\/\//}
      echo SERVER_IP=${SERVER_IP/:2375/} >> $GITHUB_ENV
    working-directory: test
    shell: bash

  - name: Set IP address to Docker container for the server
    if: ${{ inputs.where-is-client-connecting-from == 'separate-docker-container' }}
    run: echo SERVER_IP=$(docker container inspect -f '{{ .NetworkSettings.IPAddress }}' ${{ steps.get-container-name.outputs.container-name }}) >> $GITHUB_ENV
    shell: bash

  - name: Invalid input
    if: ${{ env.SERVER_IP == '' }}
    run: exit 1
    shell: bash

  - name: Get cluster name
    run: echo CLUSTER_NAME=$(docker exec ${{ steps.get-container-name.outputs.container-name }} asinfo -v "get-config:context=service" -l | grep -i cluster-name | cut -d = -f 2) >> $GITHUB_ENV
    shell: bash

  - name: Set EE server's IP address
    run: crudini --existing=param --set config.conf enterprise-edition hosts "${{ env.SERVER_IP }}:${{ env.TLS_PORT }}|${{ env.CLUSTER_NAME }}"
    working-directory: test
    shell: bash
