name: 'Run EE Server'
description: 'Run EE server. Returns once server is ready. Only tested on Linux and macOS'
inputs:
  # All inputs in composite actions are strings
  use-server-rc:
    required: true
    default: false
  server-tag:
    required: true
    default: 'latest'
  # Github Composite Actions can't access secrets
  # so we need to pass them in as inputs
  docker-hub-username:
    required: false
  docker-hub-password:
    required: false

runs:
  using: "composite"
  steps:
  - name: Install crudini to manipulate config.conf
    run: pip3 install crudini -c requirements.txt
    working-directory: .github/workflows
    shell: bash

  - name: Create config.conf
    run: cp config.conf.template config.conf
    working-directory: test
    shell: bash

  - name: Use enterprise edition instead of community edition in config.conf
    run: |
      crudini --existing=param --set config.conf enterprise-edition hosts ''
      crudini --existing=param --set config.conf enterprise-edition hosts 127.0.0.1:3000
      crudini --existing=param --set config.conf enterprise-edition user superuser
      crudini --existing=param --set config.conf enterprise-edition password superuser
    working-directory: test
    shell: bash

  - name: Create config folder to store configs in
    run: mkdir configs
    shell: bash

  - name: Log into Docker Hub to get server RC
    if: ${{ inputs.use-server-rc == 'true' }}
    run: docker login --username ${{ inputs.docker-hub-username }} --password ${{ inputs.docker-hub-password }}
    shell: bash

  - run: echo IMAGE_NAME=aerospike/aerospike-server-enterprise${{ inputs.use-server-rc == 'true' && '-rc' || '' }}:${{ inputs.server-tag }} >> $GITHUB_ENV
    shell: bash

  - run: echo SECURITY_IMAGE_NAME=${{ env.IMAGE_NAME }}-security >> $GITHUB_ENV
    shell: bash

  - name: Build and push
    uses: docker/build-push-action@v6
    with:
      # Don't want to use default Git context or else it will clone the whole Python client repo again
      context: .github/workflows
      build-args: |
        image=${{ env.IMAGE_NAME }}
      tags: ${{ env.SECURITY_IMAGE_NAME }}

  - run: docker run -d --name aerospike -p 3000:3000 ${{ env.SECURITY_IMAGE_NAME }}
    shell: bash

  - uses: ./.github/actions/wait-for-as-server-to-start
    with:
      container-name: aerospike
      is-security-enabled: true
