#!/bin/bash

# Get bash script's directory full path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change working directory to test directory
cd $DIR
PWD=`pwd` 

echo "Running test cases from ${PWD},"

# Run test suite
python3 -m pytest new_tests/
