name: aerospike-client-python

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-python:manylinux2014

build:
  - name: build
    environment:
      PYTHONS: /opt/python/cp36-cp36m/bin,/opt/python/cp37-cp37m/bin,/opt/python/cp38-cp38/bin,/opt/python/cp39-cp39/bin
    script:
      - scripts/manylinux2014build.sh
    artifact:
      - /work/wheels/*.whl
