[build-system]
requires = [
    "setuptools",
    "versioningit==3.3.0",
    # Used by our versioningit script that modifies the version
    "parver==0.5"
]
build-backend = "setuptools.build_meta"

[project]
name = "aerospike"
description = "Aerospike Client Library for Python"
authors = [
    {name = "Aerospike, Inc.", email = "info@aerospike.com"}
]
readme = "README.rst"
license = {text = "Apache Software License"}
keywords = ["aerospike", "nosql", "database"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Database"
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://aerospike.com"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.versioningit]

[tool.versioningit.vcs]
method = {module = "custom-versionit-format", value="my_vcs"}

[tool.versioningit.tag2version]
method = {module = "custom-versionit-format", value="my_tag2version"}

# Use versioneer formatting
[tool.versioningit.format]
method = {module = "custom-versionit-format", value="my_format"}
distance = "{base_version}+{distance}.{vcs}{rev}"
# Example formatted version: 1.2.3+42.ge174a1f

dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
# Example formatted version: 1.2.3+42.ge174a1f.dirty

distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
# Example formatted version: 1.2.3+42.ge174a1f.dirty

# These operations are still supported in server < 8.1.3,
# and these operations are used in many places throughout the test suite.
[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*aerospike_helpers\\.operations\\.operations\\.append.*string.*:DeprecationWarning",
    "ignore:.*aerospike_helpers\\.operations\\.operations\\.prepend.*string.*:DeprecationWarning",
]
