name: "Test CE for local build"
description: "Steps to run community edition tests for local Python client build on Ubuntu"
inputs:
  python-version:
    required: true
  server-docker-image-and-tag:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
      architecture: 'x64'

  - uses: actions/download-artifact@v3
    with:
      name: wheel-${{ inputs.python-version }}

  - name: Install client
    run: pip install *.whl
    shell: bash

  - name: Install test dependencies
    run: pip install -r test/requirements.txt
    shell: bash

  - name: Create config file using template
    run: cp config.conf.template config.conf
    working-directory: test
    shell: bash

  - name: Run Aerospike server
    run: docker run -d --name aerospike -p 3000-3002:3000-3002 ${{ inputs.server-docker-image-and-tag }}
    shell: bash

  - name: Wait for database to be ready
    # Should be ready after 3 seconds
    run: sleep 3
    shell: bash

  - name: Run tests
    run: python -m pytest ./new_tests
    working-directory: test
    shell: bash
