# This must exist until this feature request is fulfilled:
# https://github.com/actions/download-artifact/issues/141
name: 'Unwrap all artifacts'
description: 'Moves all Github Actions artifacts into a single folder called artifacts/'
inputs:
  output-folder-name:
    required: false
    default: artifacts
  artifact-filter-pattern:
    required: false
    default: "*"

runs:
  using: "composite"
  steps:
  - name: Make folder to store artifacts
    run: mkdir ${{ inputs.output-folder-name }} temp
    shell: bash

  - name: Download all artifacts that passed testing
    uses: actions/download-artifact@v3
    with:
      path: temp

  - name: Reorganize artifacts
    run: find . -type f -path "${{ inputs.artifact-filter-pattern }}" -print -exec mv {} ../artifacts/ \;
    working-directory: temp
    shell: bash

  - name: Delete artifact directories
    run: rm -r temp
    shell: bash
