from .conftest import KEYS
import unicodedata
import pytest
from aerospike_helpers.string_helpers import StringPolicy


KEY = KEYS[0]

NON_STR_BIN_NAME = INT_BIN_NAME = "nonstr"
STR_BIN_NAME = "str"
DOUBLE_BIN_NAME = "double"
BLOB_BIN_NAME = "blob"
UPPERCASE_STR_BIN_NAME = "uppercase_str"
NESTED_STR_BIN_NAME = "nested_str"
STR_WITH_INT_BIN_NAME = "str_with_int"
STR_WITH_DOUBLE_BIN_NAME = "str_with_double"
MULTIBYTE_CODEPOINT_BIN_NAME = "multibyte"
BASE64_ENCODED_BIN_NAME = "base64_enc"
SURROUNDING_WHITESPACE_BIN_NAME = "whitespace"
MULTILINE_STR_BIN_NAME = "multiline"
MULTILINE_STR_WITH_CR_BIN_NAME = "multiline_cr"

PAD_STRING = " "
SINGLE_CHAR = "z"
NEEDLE = "asdf"
EXAMPLE_STR = NEEDLE * 2
EXAMPLE_STR_WITH_SURROUNDING_WHITESPACE = " " + EXAMPLE_STR + " "
UPPERCASE_STR = EXAMPLE_STR.upper()
NOT_IN_EXAMPLE_STR = STRING_WITH_INT = "1"
STRING_WITH_DOUBLE = "2.3"
# Multi-byte representation of ñ
MULTIBYTE_CODEPOINT = "\u006E\u0303"
NORMALIZED_CODEPOINT = unicodedata.normalize("NFC", MULTIBYTE_CODEPOINT)
BASE64_ENCODED_STR = "YXNkZgo="
MULTILINE_STR = "a\na"
MULTILINE_STR_WITH_CR = "a\ra"

NEW_STR = "1234"

BINS = {
    STR_BIN_NAME: EXAMPLE_STR,
    INT_BIN_NAME: 1,
    UPPERCASE_STR_BIN_NAME: UPPERCASE_STR,
    NESTED_STR_BIN_NAME: [EXAMPLE_STR],
    STR_WITH_INT_BIN_NAME: STRING_WITH_INT,
    STR_WITH_DOUBLE_BIN_NAME: STRING_WITH_DOUBLE,
    MULTIBYTE_CODEPOINT_BIN_NAME: MULTIBYTE_CODEPOINT,
    BASE64_ENCODED_BIN_NAME: BASE64_ENCODED_STR,
    SURROUNDING_WHITESPACE_BIN_NAME: EXAMPLE_STR_WITH_SURROUNDING_WHITESPACE,
    MULTILINE_STR_BIN_NAME: MULTILINE_STR,
    MULTILINE_STR_WITH_CR_BIN_NAME: MULTILINE_STR_WITH_CR,
    DOUBLE_BIN_NAME: 1.0,
    BLOB_BIN_NAME: b'123'
}

START_IDX = 1

kwargs_policy = pytest.mark.parametrize(
    "kwargs_policy",
    [
        {"policy": None},
        {"policy": StringPolicy()}
    ]
)
