name: 'Run Server RC from Docker Hub'
description: 'Run server release candidate from Docker Hub'
inputs:
  username:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.username }}
      password: ${{ inputs.token }}

  - run: docker pull aerospike/aerospike-server-rc --all-tags
    shell: bash

  - name: Run latest rc Docker image
    run: |
      latestTag=$(docker images aerospike/aerospike-server-rc | awk 'NR==2' | awk '{print $2}')
      docker run -d --name aerospike -p 3000-3002:3000-3002 aerospike/aerospike-server-rc:$latestTag
    shell: bash
