name: 'Run enterprise edition server and setup config.conf'
inputs:
  is-client-in-another-container:
    required: true
    default: 'false'
    description: 'Is client in a Docker container separate from the server container? If false, client is running in Docker host'
  use-server-rc:
    required: true
    default: false
  server-tag:
    required: true
    default: 'latest'
  docker-hub-username:
    required: false
  docker-hub-password:
    required: false

runs:
  using: "composite"
  steps:
  - uses: ./.github/actions/run-ee-server
    id: run-ee-server
    with:
      use-server-rc: ${{ inputs.use-server-rc }}
      server-tag: ${{ inputs.server-tag }}
      docker-hub-username: ${{ inputs.DOCKER_HUB_BOT_USERNAME }}
      docker-hub-password: ${{ inputs.DOCKER_HUB_BOT_PW }}

  - uses: ./.github/actions/setup-config-conf
    with:
      using-ee-server: 'true'
      ee-host-ip-address: ${{ inputs.is-client-in-another-container == 'true' && steps.run-ee-server.outputs.server-docker-ip-address || '127.0.0.1' }}
