name: 'Wait for Aerospike server to start'
description: Only tested on Linux and macOS
inputs:
  container-name:
    required: true
    description: Server container name

runs:
  using: "composite"
  steps:
  - name: 'macOS: install timeout command'
    if: ${{ runner.os == 'macOS' }}
    run: brew install coreutils
    shell: bash

  # There is no healthcheck by default in the server Docker image,
  # and we use the default image for community edition.
  - name: Wait for EE server to start
    # Composite actions doesn't support step-level timeout-minutes, so we use timeout command.
    # Call bash shell explicitly since timeout uses "sh" shell by default, for some reason
    run: docker exec ${{ inputs.container-name }} timeout 30s bash wait-for-as-server-to-start.bash
    working-directory: .github/workflows/docker-build-context
    shell: bash
