name: 'Wait for Aerospike server to start'
inputs:
  container-name:
    required: true

runs:
  using: "composite"
  steps:
  # Composite actions doesn't support step-level timeout-minutes
  # Use timeout command, and must use shell script file for timeout
  - name: Wait for EE server to start
    run: timeout 30 ./.github/workflows/wait-for-as-server-to-start.sh ${{ inputs.container-name }}
    shell: bash
