name: 'Label JFrog build'
description: 'Label JFrog build'
inputs:
  # Github Composite Actions can't access secrets
  # so we need to pass them in as inputs
  JFROG_PLATFORM_URL:
    required: true
  JFROG_ACCESS_TOKEN:
    required: true
  build-number:
    required: true
  property-name:
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up JFrog credentials
    uses: jfrog/setup-jfrog-cli@v3
    env:
      JF_URL: ${{ inputs.JFROG_PLATFORM_URL }}
      JF_ACCESS_TOKEN: ${{ inputs.JFROG_ACCESS_TOKEN }}

  - name: Add label to build showing artifacts passed server RC tests
    run: jf rt build-promote python-client ${{ inputs.build-number }} --props "${{ inputs.property-name }}=passed"
    shell: bash
