service {
    feature-key-file /etc/aerospike/features.conf
    cluster-name docker
    proto-fd-max 15000
}

security {
    enable-quotas true
}

logging {
    console {
        context any debug
    }
}

network {
    tls aerospike-tls {
        cert-file /etc/aerospike/tls/server.crt
        key-file  /etc/aerospike/tls/server.key
        ca-file   /etc/aerospike/tls/ca.crt
    }
    service {
        address any
        port 3000
        tls-port 4333
        tls-authenticate-client false
        tls-name aerospike-tls
    }
    heartbeat {
        mode mesh
        port 3002
    }
    fabric {
        port 3001
    }
}

namespace test {
    replication-factor 1
    strong-consistency true
    strong-consistency-allow-expunge true
    default-ttl 30d
    allow-ttl-without-nsup true
    storage-engine device {
        file /opt/aerospike/data/test.dat
        filesize 4G
    }
}
