name: Build sanitizer wheel

on:
  workflow_dispatch:
  pull_request:

jobs:
  sanitizer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add local version specifier to version
      run: |
        version=$(cat VERSION)
        version="$version+sanitizer"
        echo $version > VERSION
        sed -i "s/const char version\[] = \".*\";/const char version\[] = \"$version\";/" src/main/aerospike.c

    - name: Build wheel
      uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_BUILD: cp38-manylinux_x86_64
        CIBW_BUILD_FRONTEND: build
        CIBW_BEFORE_ALL_LINUX: >
          yum install openssl-devel -y &&
          yum install python-devel -y &&
          yum install python-setuptools -y
        CIBW_ARCHS: "x86_64"
        CIBW_ENVIRONMENT_PASS_LINUX: SANITIZER

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ secrets.JFROG_URL }}
        user: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_ACCESS_TOKEN }}
        packages-dir: wheelhouse/
        verbose: true
