on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  windows-python-dbg:
    runs-on: ["self-hosted", "Windows", "X64"]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - name: Get tests and Github action scripts
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ inputs.use_jfrog_builds && inputs.jfrog-build-version-to-test || github.sha }}

    # I believe pyenv is more suited for user installations. Installing on Github Actions means installing as administrator
    # When doing so, pyenv could not be called automatically even after setting the PATH.
    - run: |
        $python_version = "3.10.11"
        $installer = "python-$python_version-amd64.exe"
        Invoke-WebRequest https://www.python.org/ftp/python/$python_version/$installer -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList "/passive", "/quiet", "InstallAllUsers=1", "PrependPath=1", "Include_debug=1" -Wait

    - uses: ./.github/actions/run-ee-server
      with:
        # registry-name: ${{ inputs.registry-name }}
        registry-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
        registry-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
        # image-name: ${{ inputs.image-name }}
        # server-tag: ${{ inputs.server-tag }}
        where-is-client-connecting-from: 'remote-connection'

    - name: Install wheel
      run: |
        python_d -m pip install build -c requirements.txt
        python_d -m pip -m build
        python_d -m pip install dist/*.whl

    - name: Install test dependencies
      run: python_d -m pip install pytest -c requirements.txt
      working-directory: test

    - name: Run tests
      run: python_d -m pytest new_tests/
      working-directory: test
