permissions:
  statuses: write
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      test-definition:
        required: true
        description: Test definition

jobs:
  build-wheel-for-feature-branch:
    uses: ./.github/workflows/build-and-optionally-test-wheels-on-one-platform.yml
    with:
      # TODO: single source
      platform-tag: manylinux_x86_64
      python-versions: '["3.10"]'
    secrets: inherit

  run-qe-test:
    needs: build-wheel-for-feature-branch
    uses: ./.github/workflows/run-qe-test.yml
    with:
      get-wheel-from-jfrog: false
      test-definition: ${{ inputs.test-definition }}
      # CLIENT-4733-migrate-from-internal-ansible-api-to-ansible-runner-to-clean-up-technical-debt
      test-code-revision: af16b3a63c8852760ad78c64301135adb55dfdeb
      qe-docker-revision: cicd-client-performance-regression-tests-requirements-txt
    secrets: inherit
