name: Build and test wheels on self-hosted runners

on:
  workflow_dispatch:
    inputs:
      python-tags:
        type: string
        description: Python versions to build and test the client on
        required: false
        default: '["cp38", "cp39", "cp310", "cp311", "cp312"]'
      platform-tag:
        type: string
        required: true
        default: win_amd64
      runner-os:
        type: string
        required: true
        default: windows-2022
      self-hosted-tags:
        type: string
        required: true
        default: '["self-hosted", "Windows", "X64"]'
      use-server-rc:
        type: boolean
        required: true
        default: false

jobs:
  build-wheels:
    uses: ./.github/workflows/cibuildwheel.yml
    with:
      platform-tag: ${{ inputs.platform-tag }}
      python-tags: ${{ inputs.python-tags }}
      runner-os: ${{ inputs.runner-os }}

  test-wheels-on-self-hosted:
    needs: build-wheels
    strategy:
      matrix:
        python-tag: ${{ fromJson(inputs.python-tags) }}
      fail-fast: false
    uses: ./.github/workflows/download-and-test-wheel.yml
    with:
      python-version: ${{  }}
