name: 'Build wheels'
run-name: 'Build wheels (python-versions=${{ inputs.python-versions }}, platform-tag=${{ inputs.platform-tag }}, unoptimized=${{ inputs.unoptimized }}, include-debug-info-for-macos=${{ inputs.include-debug-info-for-macos }}, run_tests=${{ inputs.run_tests }}, registry-name=${{ inputs.registry-name }}, image-name=${{ inputs.image-name }}, server-tag=${{ inputs.server-tag }}), test-file=${{ inputs.test-file }}'

# Build wheels on all (or select) Python versions supported by the Python client for a specific platform

permissions:
  id-token: write
  contents: read
  statuses: write

on:
  workflow_dispatch:
    inputs:
      # These are the usual cases for building wheels:
      #
      # 1. One wheel for *one* supported Python version. This is for running specialized tests that only need one Python version
      # like valgrind or a failing QE test. And usually, we only need one wheel for debugging purposes.
      # 2. Wheels for *all* supported Python versions for *one* supported platform. This is useful for testing workflow changes for a
      # single OS or CPU architecture (e.g testing that changes to debugging modes work on all Python versions)
      # 3. Wheels for *all* supported Python versions and *all* supported platforms. This is for building wheels for different
      # CI/CD stages (e.g dev, stage, or master). We can also test debugging modes for all platforms that support them
      #
      # We're able to combine case 1 and 2 into one workflow by creating an input that takes in a JSON list of strings (Python tags)
      # to build wheels for. Actual list inputs aren't supported yet, so it's actually a JSON list encoded as a string.
      #
      # However, it's harder to combine this workflow (case 1 + 2) with case 3, because matrix outputs don't exist yet
      # in Github Actions. So all jobs in the cibuildwheel job would have to pass for a self hosted job to run.
      # We want each platform to be tested independently of each other,
      # so there is a wrapper workflow that has a list of platforms to test and reuses this workflow for each platform.
      # If one platform fails, it will not affect the building and testing of another platform (we disable fail fast mode)
      python-versions:
        type: string
        description: Valid JSON list of Python tags to build the client for. If empty, build for all supported python versions
        required: false
        default: '*'
      platform-tag:
        description: Platform to build the client for.
        type: choice
        required: true
        options:
        - manylinux_x86_64
        - manylinux_aarch64
        - macosx_x86_64
        - macosx_arm64
        - win_amd64
        # Makes debugging via gh cli easier.
        default: manylinux_x86_64
      unoptimized:
        description: 'macOS or Linux: Apply -O0 flag?'
        # Windows supports a different flag to disable optimizations, but we haven't added support for it yet
        type: boolean
        required: false
        default: false
      include-debug-info-for-macos:
        description: 'macOS: Build wheels for debugging?'
        type: boolean
        required: false
        default: false
      run_tests:
        description: 'Run Aerospike server and run tests using built wheels?'
        type: boolean
        required: false
        default: false
      registry-name:
        type: string
        required: false
        description: Registry name
        default: 'docker.io'
      image-name:
        type: string
        required: false
        description: Image name
        default: 'aerospike/aerospike-server-enterprise'
      server-tag:
        required: true
        default: 'latest'
        description: 'Server docker image tag'
      test-file:
        required: false
        default: ''
        description: 'new_tests/<value>'

  workflow_call:
    inputs:
      # See workflow call hack in update-version.yml
      is_workflow_call:
        type: boolean
        default: true
        required: false
      python-versions:
        type: string
        description: Valid JSON list of Python tags to build the client for. If empty, build for all supported python versions
        required: false
        default: '*'
      platform-tag:
        type: string
        required: true
      unoptimized:
        type: boolean
        required: false
        default: false
      include-debug-info-for-macos:
        type: boolean
        required: false
        default: false
      run_tests:
        type: boolean
        required: false
        default: false
      registry-name:
        type: string
        required: false
        default: 'docker.io'
      image-name:
        type: string
        required: false
        default: 'aerospike/aerospike-server-enterprise'
      server-tag:
        required: false
        type: string
        default: 'latest'
        description: 'Server docker image tag'
      test-file:
        required: false
        type: string
        default: ''
    secrets:
      # Just make all the secrets required to make things simpler...
      DOCKER_HUB_BOT_USERNAME:
        required: true
      DOCKER_HUB_BOT_PW:
        required: true
      QE_DOCKER_REGISTRY_USERNAME:
        required: true
      QE_DOCKER_REGISTRY_PASSWORD:
        required: true
      MAC_M1_SELF_HOSTED_RUNNER_PW:
        required: true

env:
  # Note that environment variables in Github are all strings
  # Github mac m1 and windows runners don't support Docker / nested virtualization
  # so we need to use self-hosted runners to test wheels for these platforms
  REGISTRY_USERNAME: ${{ inputs.registry-name == 'docker.io' && secrets.DOCKER_HUB_BOT_USERNAME || secrets.QE_DOCKER_REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ inputs.registry-name == 'docker.io' && secrets.DOCKER_HUB_BOT_PW || secrets.QE_DOCKER_REGISTRY_PASSWORD }}

jobs:
  # Maps don't exist in Github Actions, so we have to store the map using a script and fetch it in a job
  # This uses up more billing minutes (rounded up to 1 minute for each job run),
  # but this should be ok based on the minutes usage data for the aerospike organization
  get-runner-os-and-all-python-versions:
    uses: ./.github/workflows/get-platform-info-and-all-supported-python-versions.yml
    with:
      platform-tag: ${{ inputs.platform-tag }}

  build-wheel:
    needs: get-runner-os-and-all-python-versions
    strategy:
      matrix:
        python-version: ${{ inputs.python-versions == '*' && fromJson(needs.get-runner-os-and-all-python-versions.outputs.python-versions) || fromJson(inputs.python-versions) }}
      fail-fast: false
    runs-on: ${{ needs.get-runner-os-and-all-python-versions.outputs.runner-os }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.python-version }}-${{ inputs.platform-tag }}"
      RUN_INTEGRATION_TESTS_IN_THIS_JOB: ${{ inputs.run_tests && (startsWith(inputs.platform-tag, 'manylinux') || inputs.platform-tag == 'macosx_x86_64') }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="build-wheel (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
      shell: bash

    - name: Show job status for commit
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
      with:
        sha: ${{ github.sha }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: recursive
        # We need the last tag before the ref, so we can relabel the version if needed
        fetch-depth: 0

    - name: 'Windows: Add msbuild to PATH'
      if: ${{ inputs.platform-tag == 'win_amd64' }}
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ env.RUN_INTEGRATION_TESTS_IN_THIS_JOB == 'true' && inputs.platform-tag == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - name: 'Run Aerospike server in Docker container and configure tests accordingly'
      if: ${{ env.RUN_INTEGRATION_TESTS_IN_THIS_JOB == 'true' }}
      uses: ./.github/actions/run-ee-server
      with:
        registry-name: ${{ inputs.registry-name }}
        registry-username: ${{ env.REGISTRY_USERNAME }}
        registry-password: ${{ env.REGISTRY_PASSWORD }}
        image-name: ${{ inputs.image-name }}
        server-tag: ${{ inputs.server-tag }}
        where-is-client-connecting-from: ${{ inputs.platform-tag == 'macosx_x86_64' && 'docker-host' || 'separate-docker-container' }}

    - name: Set unoptimize flag
      if: ${{ inputs.unoptimized && (startsWith(inputs.platform-tag, 'manylinux') || startsWith(inputs.platform-tag, 'macosx')) }}
      run: echo "UNOPTIMIZED=1" >> $GITHUB_ENV

    - name: Set include dsym flag
      if: ${{ inputs.include-debug-info-for-macos && startsWith(inputs.platform-tag, 'macosx') }}
      run: echo "INCLUDE_DSYM=1" >> $GITHUB_ENV

    # OpenSSL locked version for this git revision: 3.0.15
    # We lock the digest for security reasons.

    - if: ${{ startsWith(inputs.platform-tag, 'manylinux') }}
      name: Setup JFrog CLI
      id: setup-jf
      uses: jfrog/setup-jfrog-cli@1641575d87647fb969c0545f0b6a76873e328b7c # v5.0.0
      env:
        JF_URL: https://${{ vars.JF_EXTERNAL_URL }}
      with:
        version: '2.92.0'
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}

    - if: ${{ startsWith(inputs.platform-tag, 'manylinux') }}
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ${{ vars.JF_EXTERNAL_URL }}/${{ vars.JFROG_REPO_FOR_CUSTOM_MANYLINUX_IMAGES }}
        username: ${{ steps.setup-jf.outputs.oidc-user }}
        password: ${{ steps.setup-jf.outputs.oidc-token }}


    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Build wheel
      run: KEEP_CONTAINER=1 ./build-prod-wheel.bash
      shell: bash
      env:
        MANYLINUX_REGISTRY_NAME: ${{ vars.JF_EXTERNAL_URL }}/${{ vars.JFROG_REPO_FOR_CUSTOM_MANYLINUX_IMAGES }}
        PYTHON_VERSION: ${{ matrix.python-version }}

    # - name: Setup tmate session
    #   if: ${{ !cancelled() }}
    #   uses: mxschmitt/action-tmate@v3

    # For debugging
    - run: |
        # Checks that server started up properly
        docker logs aerospike
      if: ${{ always() && env.RUN_INTEGRATION_TESTS_IN_THIS_JOB == 'true' }}
      shell: bash

    - name: Upload wheels to GitHub
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: ${{ !cancelled() }}
      with:
        path: ./wheelhouse/*.whl
        name: ${{ env.BUILD_IDENTIFIER }}.build
        if-no-files-found: error

    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
      with:
        sha: ${{ github.sha }}
        status: ${{ job.status }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}

  test-self-hosted:
    needs: build-wheel
    # There's a top-level env variable for this but we can't use it here, unfortunately
    if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    runs-on: ${{ inputs.platform-tag == 'macosx_arm64' && fromJSON('["self-hosted", "macOS", "ARM64"]') || fromJSON('["self-hosted", "Windows", "X64"]') }}
    env:
      BUILD_IDENTIFIER: "${{ matrix.python-version }}-${{ inputs.platform-tag }}"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Create status check message
        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
        shell: bash

      - name: Show job status for commit
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
        with:
          sha: ${{ github.sha }}
          context: ${{ env.STATUS_CHECK_MESSAGE }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Need to be able to save Docker Hub credentials to keychain
      # Unable to do this via the ansible script for self hosted mac m1 runners
      - if: ${{ inputs.platform-tag == 'macosx_arm64' }}
        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}

      - uses: ./.github/actions/run-ee-server
        with:
          registry-name: ${{ inputs.registry-name }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-password: ${{ env.REGISTRY_PASSWORD }}
          image-name: ${{ inputs.image-name }}
          server-tag: ${{ inputs.server-tag }}
          where-is-client-connecting-from: ${{ inputs.platform-tag == 'win_amd64' && 'remote-connection' || 'docker-host' }}

      - name: Download wheel
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.BUILD_IDENTIFIER }}.build

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install wheel
        run: python3 -m pip install aerospike --force-reinstall --no-index --find-links=./
        shell: bash

      - run: python3 -m pip install pytest -c requirements.txt
        working-directory: test
        shell: bash

      - run: python3 -m pytest -vvs --full-trace new_tests/${{ inputs.test-file }}
        working-directory: test
        shell: bash

      - name: Show job status for commit
        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ github.sha }}
          status: ${{ job.status }}
          context: ${{ env.STATUS_CHECK_MESSAGE }}
