# Takes in how to bump version as input
# Bumps current version to new version, and tags new version

permissions:
  contents: write

name: Bump version
on:
  push:
    branches:
    - 'dev*'
    tags-ignore:
    - '*'
  # For debugging
  workflow_dispatch:
    inputs: &inputs
      bump-type-for-new-tag:
        # - bump-dev-num
        # - strip_prerelease_part
        type: string
        description: Type of change to make to existing version
        required: true
      dry-run:
        required: false
        default: false
        type: boolean
        description: No tagging in repo
  workflow_call:
    inputs: *inputs

jobs:
  apply-change-to-version-and-tag:
    name: Get new version string
    runs-on: ubuntu-22.04
    steps:
    # Checkout the branch where we want to bump the new version
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        # Get all tags
        fetch-depth: 0

    - name: Get tag from commit before push
      id: get-current-version
      run: |
        prev_commit=$(git rev-parse HEAD~)
        echo current_version=$(git describe --tags --exact-match $prev_commit) >> $GITHUB_OUTPUT

    - name: Install library that parses PEP 440 versions
      run: pip install parver -c requirements.txt
      working-directory: .github/workflows

    - name: Get new version
      id: get-new-version
      run: echo new_version=$(python3 .github/workflows/${CHANGE_VERSION_SCRIPT_NAME}.py "${CURRENT_VERSION}") >> $GITHUB_OUTPUT
      env:
        CURRENT_VERSION: ${{ steps.get-current-version.outputs.current_version }}
        CHANGE_VERSION_SCRIPT_NAME: ${{ inputs.bump-type-for-new-tag }}

    - name: Compare current and next release version
      id: get-current-and-next-release-version
      run: |
        next_version=$(python3 .github/workflows/strip_prerelease_part.py "${{ steps.get-new-version.outputs.new_version }}") >> $GITHUB_OUTPUT
        current_release_version=$(cat VERSION) >> $GITHUB_OUTPUT

    - if: ${{ inputs.dry-run == false && steps.get-current-and-next-release-version.outputs.current_release_version != steps.get-current-and-next-release-version.outputs.next_version }}
      name: Update version in repo
      uses: ./.github/actions/update-version
      with:
        new_version: ${{ steps.get-current-and-next-release-version.outputs.next_version }}

    - if: ${{ inputs.dry-run == false }}
      run: |
        git tag $NEW_VERSION
        git push origin tag $NEW_VERSION
      env:
        NEW_VERSION: ${{ steps.get-new-version.outputs.new_version }}
