# Takes in how to bump version as input
# Tags version and outputs the new tagged version

name: Bump version
on:
  workflow_dispatch:
    inputs:
      change:
        type: choice
        description: Type of change to make to existing version
        required: true
        options:
        - bump-dev-num
        - promote-dev-version-to-release-version
      dry-run:
        required: false
        default: false
        type: boolean
        description: No tagging in repo
  workflow_call:
    inputs:
      dry-run:
        required: false
        default: false
        type: boolean
        description: No tagging in repo
      change:
        type: string
        description: Type of change to make to existing version
        required: true
      ref:
        required: false
        description: Commit to tag
        type: string
      # See workflow call hack in update-version.yml
      is_workflow_call:
        type: boolean
        default: true
        required: false
    outputs:
      new_version:
        value: ${{ jobs.get-new-version.outputs.new_version }}

jobs:
  get-current-version:
    name: Get new version string
    runs-on: ubuntu-22.04
    outputs:
      current_version: ${{ steps.get-current-version.outputs.current_version }}
    steps:
    # Checkout the branch where we want to bump the new version
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ inputs.ref }}
        # Get all tags
        fetch-depth: 0

    - name: Get tag from commit before push
      id: get-current-version
      run: |
        prev_commit=$(git rev-parse HEAD~)
        echo current_version=$(git describe --tags --exact-match $prev_commit) >> $GITHUB_OUTPUT

    - name: Install library that parses PEP 440 versions
      run: pip install parver -c requirements.txt
      working-directory: .github/workflows

    - name: Get new version
      id: get-new-version
      run: echo new_version=$(python3 .github/workflows/${CHANGE_VERSION_SCRIPT_NAME}.py "${CURRENT_VERSION}") >> $GITHUB_OUTPUT
      env:
        CURRENT_VERSION: ${{ steps.get-current-version.outputs.current_version }}
        CHANGE_VERSION_SCRIPT_NAME: ${{ inputs.change }}

    - if: ${{ inputs.dry-run == false }}
      run: |
        git tag $NEW_VERSION
        git push origin tag $NEW_VERSION
      env:
        NEW_VERSION: ${{ steps.get-new-version.outputs.new_version }}
