permissions:
  id-token: write

name: Upload to JFrog

on:
  workflow_call:
    inputs:
      dry-run:
        required: false
        default: false
        type: boolean
        description: "Don't upload to jfrog"
      dir-to-store-artifact:
        required: true
        type: string
        description: Repo name + path to upload to JFrog

jobs:
  upload-to-jfrog:
    env:
      ARTIFACTS_DEST_DIR: artifacts
    name: Upload artifacts to JFrog
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: ${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}*
        merge-multiple: true
        path: ${{ env.ARTIFACTS_DEST_DIR }}

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@3054b554c0fb4915b3d58847fb7730c593dbb934 # v5.0.0
      env:
        JF_URL: https://${{ vars.JF_EXTERNAL_URL }}
        JF_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      with:
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}

    - if: ${{ inputs.dry-run }}
      run: echo "DRY_RUN_FLAG=--dry-run" >> "$GITHUB_ENV"

    - name: Upload manylinux build from feature branch to JFrog generic repo
      run: |
        # shellcheck disable=SC2086
        jf rt upload $DRY_RUN_FLAG "*manylinux*" "$DIR_TO_STORE_ARTIFACT/"
      working-directory: ${{ env.ARTIFACTS_DEST_DIR }}
      env:
        DIR_TO_STORE_ARTIFACT: ${{ inputs.dir-to-store-artifact }}
