on:
  workflow_call:
    inputs:
      earlier_rev:
        type: string
        required: true
      later_rev:
        type: string
        required: true
    outputs:
      run_integration_tests:
        value: ${{ jobs.compare-two-revs.outputs.run_integration_tests }}
      later_rev_tag:
        value: ${{ jobs.compare-two-revs.outputs.later_rev_tag }}

jobs:
  compare-two-revs:
    outputs:
      run_integration_tests: ${{ steps.run_integration_tests.outputs.run_integration_tests }}
      later_rev_tag: ${{ steps.run_integration_tests.outputs.later_rev_tag }}
    env:
      EARLIER_REV: ${{ inputs.earlier_rev }}
      LATER_REV: ${{ inputs.later_rev }}
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        # Get all commits
        fetch-depth: 0

    # We want to skip the integration tests if the changes made between the two commits wouldn't affect the results of the integration tests
    # TODO: update whitelisted changes
    - name: Decide whether to skip integration tests
      id: run_integration_tests
      run: |
        # '|| true' required since grep returns non-zero status code when no matches are found
        num_files_changed=$(git diff "origin/$EARLIER_REV..origin/$LATER_REV" --name-only | \
          grep --invert-match --count \
          -e "^doc/" \
          -e "^aerospike-stubs/" \
          -e VERSION \
          || true)

        # If any files were changed besides the exceptions, run the integration tests
        run_tests() {
          if [[ "$num_files_changed" = "0" ]]; then
            echo false
          else
            echo true
          fi
        }
        echo run_integration_tests=$(run_tests) >> "$GITHUB_OUTPUT"

        # Sanity check
        # Make sure the earlier revision being compared to has a release bundle (we use tags as a proxy to tell)
        # Otherwise we may have missed testing changes from the last time we ran integration tests
        git describe --tags --exact-match "origin/$EARLIER_REV"

        # Fail if we can't find a tag for the later revision
        shopt -s inherit_errexit
        echo later_rev_tag=$(git describe --tags --exact-match "origin/$LATER_REV") >> "$GITHUB_OUTPUT"
      # We want this step to fail if a command failed while using pipes
      shell: bash
