on:
  workflow_call:
    inputs:
      earlier_rev:
        type: string
        required: true
      later_rev:
        type: string
        required: true
    outputs:
      run_integration_tests:
        value: ${{ jobs.compare-two-revs.outputs.run_integration_tests }}
      later_rev_tag:
        value: ${{ jobs.compare-two-revs.outputs.later_rev_tag }}

permissions:
  contents: read

jobs:
  compare-two-revs:
    outputs:
      run_integration_tests: ${{ steps.run_integration_tests.outputs.run_integration_tests }}
      # For stage workflow to get the JFrog release bundle to test
      later_rev_tag: ${{ steps.run_integration_tests.outputs.later_rev_tag }}
    env:
      EARLIER_REV: ${{ inputs.earlier_rev }}
      LATER_REV: ${{ inputs.later_rev }}
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # Get all commits
        fetch-depth: 0

    # We want to skip the integration tests if the changes made between the two commits wouldn't affect the results of the integration tests
    # TODO: update whitelisted changes
    - name: Decide whether to skip integration tests
      id: run_integration_tests
      run: |
        # Fail inside command substitution
        shopt -s inherit_errexit

        # '|| true' required since grep returns non-zero status code when no matches are found
        files_changed=$(git diff "$EARLIER_REV..$LATER_REV" --name-only)
        num_files_changed=$(echo "$files_changed" | \
          grep --invert-match --count \
          -e "^doc/" \
          -e "^aerospike-stubs/" \
          -e VERSION \
          || true)

        # If any files were changed besides the exceptions, run the integration tests
        run_tests() {
          if [[ "$num_files_changed" = "0" ]]; then
            echo false
          else
            echo true
          fi
        }
        echo "run_integration_tests=$(run_tests)" >> "$GITHUB_OUTPUT"

        # Sanity check
        # Make sure the earlier revision being compared to has a release bundle (we use tags as a proxy to tell)
        # Otherwise there may have been changes before the earlier revision that weren't tested
        git describe --tags --exact-match "$EARLIER_REV"

        # Fail if we can't find a tag for the later revision
        echo "later_rev_tag=$(git describe --tags --exact-match "$LATER_REV")" >> "$GITHUB_OUTPUT"
      # We want this step to fail if a command failed while using pipes
      shell: bash -exo pipefail {0}
