name: Run dev tests and promote release bundle to DEV
run-name: Run dev tests and promote release bundle to DEV (dry-run=${{ inputs.dry-run }}, server-tag=${{ inputs.server-tag }}, test-file=${{ inputs.test-file }})

on:
  workflow_dispatch:
    inputs:
      server-tag:
        type: string
        # latest tag is not supported in JFrog
        required: true
        description: 'Server docker image tag'
      # For testing purposes
      dry-run:
        required: false
        default: false
        type: boolean
        description: Don't publish JFrog build info or create a JFrog build + release bundle
      run_tests:
        required: false
        default: true
        type: boolean
        description: Run dev tests. For speeding up debugging
      test-file:
        required: false
        type: string
        description: For speeding up debugging

jobs:
  get-last-release-bundle-info:
    uses: ./.github/workflows/get-latest-release-bundle.yml
    permissions:
      id-token: write

  get-this-jfrog-build-info:
    outputs:
      jfrog_build_id: ${{ steps.get-jfrog-build-id.outputs.id }}
      # Used downstream for labelling the JFrog build with a version
      next-release-version: ${{ steps.get-next-release-version.outputs.next_release_version }}
      # Used downstream to tag the release bundle
      latest-tag: ${{ steps.get-latest-tag.outputs.latest_tag }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0

    - id: get-next-release-version
      run: echo "next_release_version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

    - name: Safeguard to make sure there's changes in dev to be promoted
      id: get-latest-tag
      run: |
        latest_tag=$(git describe --tags --exact-match HEAD)
        if [[ "$latest_tag" == "$next_release_version" ]]; then
          echo "We have not merged any changes to dev since the last release yet." >&2
          exit 1
        fi
        echo latest_tag="$latest_tag" >> "$GITHUB_OUTPUT"

    - id: get-jfrog-build-id
      # Following this convention to be consistent with company policy (instead of using tags for JFrog build id)
      run: echo id=${{ github.run_id }}-${{ github.run_attempt }} >> "$GITHUB_OUTPUT"

  compare-last-release-bundle-rev-with-latest-dev-tag:
    needs: [
      get-last-release-bundle-info,
      get-this-jfrog-build-info
    ]
    uses: ./.github/workflows/decide-to-run-integration-tests.yml
    with:
      earlier_rev: ${{ needs.get-last-release-bundle-info.outputs.release-bundle-tag }}
      later_rev: ${{ needs.get-this-jfrog-build-info.outputs.latest-tag }}

  build-artifacts:
    needs: get-this-jfrog-build-info
    uses: ./.github/workflows/build-artifacts.yml
    with:
      run_tests: ${{ inputs.run_tests }}
      run-integration-tests-on-macos-x86: false
      publish-build-info: ${{ inputs.dry-run == false }}
      server-tag: ${{ inputs.server-tag }}
      test-file: ${{ inputs.test-file }}
      # Needed for collecting build info
      jf-build-id: ${{ needs.get-this-jfrog-build-info.outputs.jfrog_build_id }}
    permissions:
      contents: read
      # For shared reusable workflows
      id-token: write
      statuses: write
    secrets: inherit

  valgrind:
    needs: build-artifacts
    uses: ./.github/workflows/test-artifact.yml
    with:
      runner-os-json-string: '"ubuntu-22.04"'
      # Get lowest supported python version
      python-version: ${{ fromJson(needs.build-artifacts.outputs.python-versions)[0] }}
      server-tag: ${{ inputs.server-tag }}
      test-file: ${{ inputs.test-file }}
      run-with-valgrind: true
      run-valgrind-with-massif: false
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      statuses: write

  reupload-artifacts-as-one-artifact-in-github:
    needs: [
      valgrind
    ]
    runs-on: ubuntu-24.04
    permissions:
      actions: read
    env:
      ARTIFACT_NAME: build-artifacts
    outputs:
      artifact-name: ${{ env.ARTIFACT_NAME }}
    steps:
    - id: reupload
      uses: aerospike/shared-workflows/.github/actions/collect-build-artifacts@1004088a1b5122b9b71a39b40f619f6b50e78d16
      with:
        # This is the default name, but setting here explicitly in case updating this composite action causes artifact name
        # to change unexpectedly.
        output-name: ${{ env.ARTIFACT_NAME }}

  upload-artifacts-to-jfrog:
    needs: [
      get-this-jfrog-build-info,
      reupload-artifacts-as-one-artifact-in-github
    ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_deploy-artifacts.yaml@1004088a1b5122b9b71a39b40f619f6b50e78d16
    with:
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      jf-build-name: ${{ vars.JFROG_BUILD_NAME }}
      # Have to override the default artifact name because we are not signing the artifacts
      gh-artifact-name: ${{ needs.reupload-artifacts-as-one-artifact-in-github.outputs.artifact-name }}
      jf-build-id: ${{ needs.get-this-jfrog-build-info.outputs.jfrog_build_id }}
      jf-metadata-build-id: ${{ needs.get-this-jfrog-build-info.outputs.jfrog_build_id }}-buildinfo
      version: ${{ needs.get-this-jfrog-build-info.outputs.next-release-version }}
      gh-workflows-ref: 1004088a1b5122b9b71a39b40f619f6b50e78d16
      dry-run: ${{ inputs.dry-run }}
    permissions:
      contents: read
      id-token: write
      actions: read

  create-release-bundle:
    if: ${{ inputs.dry-run == false }}
    needs: [
      upload-artifacts-to-jfrog,
      get-this-jfrog-build-info
    ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@1004088a1b5122b9b71a39b40f619f6b50e78d16
    with:
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      jf-build-names: |
        ${{ vars.JFROG_BUILD_NAME }}:${{ needs.get-this-jfrog-build-info.outputs.jfrog_build_id }}
      jf-bundle-name: ${{ vars.JFROG_RELEASE_BUNDLE_NAME }}
      # JFrog release bundle version
      version: ${{ needs.get-this-jfrog-build-info.outputs.next-release-version }}
      gh-workflows-ref: 1004088a1b5122b9b71a39b40f619f6b50e78d16 # Should match the version in your 'uses:' line
    permissions:
      contents: read
      id-token: write

  promote-release-bundle-to-dev:
    needs: [
      get-this-jfrog-build-info,
      create-release-bundle
    ]
    uses: ./.github/workflows/promote-and-optionally-tag-release-bundle.yml
    with:
      jfrog-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      release-bundle-name: ${{ vars.JFROG_RELEASE_BUNDLE_NAME }}
      release-bundle-version: ${{ needs.get-this-jfrog-build-info.outputs.next-release-version }}
      release-bundle-tag: ${{ needs.get-this-jfrog-build-info.outputs.latest-tag }}
      new-environment: DEV
    permissions:
      id-token: write
