name: Dev workflow (part 2)

on:
  # This will ignore bump commits because those commits have [skip ci]
  push:
    branches:
    - 'dev*'
  workflow_dispatch:
    inputs:
      dry-run:
        description: Don't create tag in repo
        type: boolean
        required: false
        default: true

jobs:
  tag-new-commit-with-dev-number:
    uses: ./.github/workflows/bump-dev-number-and-tag-commit.yml
    with:
      change: 'bump-dev-num'
      dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || false }}
    secrets: inherit
