name: Stage tests

on:
  # Should be run from the dev branch usually
  workflow_dispatch:

jobs:
  get-latest-tag:
    outputs:
      latest-dev-version: ${{ steps.get-dev-version.outputs.latest-dev-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Get all tags
        fetch-depth: 0
    - name: Get latest dev version
      run: echo latest-dev-version=$(git describe --abbrev=0) >> $GITHUB_OUTPUT
      id: get-dev-version

  run-stage-tests:
    uses: ./.github/workflows/stage-tests.yml
    needs: get-latest-tag
    with:
      use-server-rc: false
      commit_sha: ${{ needs.get-latest-tag.outputs.latest-dev-version }}
    secrets: inherit

  fast-forward-stage-to-dev:
    name: Fast forward stage to tested commit in dev
    needs: run-stage-tests
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      branch_to_merge: ${{ needs.get-latest-tag.outputs.latest-dev-version }}
      base_branch: stage-test
    secrets: inherit

  promote-dev-build-to-rc:
    needs: fast-forward-stage-to-dev
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'promote-dev-build-to-rc'
      commit_sha: stage-test
    secrets:
      CLIENT_BOT_PAT: ${{ secrets.CLIENT_BOT_PAT }}

  delete-dev-artifacts:
    needs: promote-dev-build-to-rc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # We can't upload to the same artifact name with upload-artifact@v4
      # So we must delete the artifacts produced by stage-tests.yml
      # Before rebuilding the artifacts with the new RC version
      - name: Remove artifacts with dev version
        uses: geekyeggo/delete-artifact@v2
        with:
          name: '*.build'

  rebuild-artifacts-with-rc-version:
    needs: delete-dev-artifacts
    uses: ./.github/workflows/build-wheels.yml
    with:
      run_tests: false
      commit_sha: ${{ inputs.commit_sha }}

  filter-artifacts:
    if: ${{ !cancelled() }}
    needs: rebuild-artifacts-with-rc-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/workflows/filter-artifacts.py
        sparse-checkout-cone-mode: false

    - uses: actions/download-artifact@v4
      with:
        pattern: '*.matrix-output'
        path: matrix-outputs
        merge-multiple: true

    - name: Filter artifacts
      run: python3 filter-artifacts.py
      working-directory: ./.github/workflows/

    - run: |
        {
          echo 'bad_artifacts<<EOF'
          cat failed_artifacts.txt
          echo EOF
        } >> $GITHUB_OUTPUT
      id: bad-artifacts
      working-directory: ./.github/workflows/

    # We don't need matrix output files anymore after this job
    - name: Remove failed artifacts and matrix outputs
      uses: geekyeggo/delete-artifact@v2
      with:
        name: |
          ${{ steps.bad-artifacts.outputs.bad_artifacts }}
          *.matrix-output

  upload-to-jfrog:
    needs: [
      promote-dev-build-to-rc,
      filter-artifacts
    ]
    name: Upload artifacts to JFrog
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.promote-dev-build-to-rc.outputs.new_version }}
    secrets: inherit

  check-for-dev-changes:
    needs: upload-to-jfrog
    runs-on: ubuntu-latest
    outputs:
      no-dev-changes-detected: ${{ steps.check-new-changes.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev-test
          token: ${{ secrets.CLIENT_BOT_PAT }}
          fetch-depth: '0'

      - name: Get commit hash of tested version
        run: echo TESTED_VERSION_COMMIT=$(git rev-list -n 1 ${{ needs.get-latest-tag.outputs.latest-dev-version }}) >> $GITHUB_ENV

      - name: Get latest commit hash of dev
        run: echo LATEST_DEV_COMMIT=$(git log -n 1 dev-test) >> $GITHUB_ENV

      - name: Check for new changes since tested version in dev
        id: check-new-changes
        run: test $TESTED_VERSION_COMMIT = $LATEST_DEV_COMMIT

      - name: If new changes in dev, force merge stage's RC version into dev
        if: ${{ steps.check-new-changes.outcome == 'failure' }}
        run: git merge -X theirs stage-test

      - name: Push changes to remote dev
        if: ${{ steps.check-new-changes.outcome == 'failure' }}
        run: git push

  bump-to-new-dev-version:
    needs: check-for-dev-changes
    if: ${{ needs.check-for-dev-changes.outputs.no-dev-changes-detected == 'false' }}
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
      commit_sha: dev-test
    secrets: inherit

  ff-dev-to-stage:
    needs: [
      check-for-dev-changes,
      promote-dev-build-to-rc
    ]
    if: ${{ needs.check-for-dev-changes.outputs.no-dev-changes-detected == 'true' }}
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      branch_to_merge: ${{ needs.promote-dev-build-to-rc.outputs.bump_sha }}
      base_branch: dev-test
    secrets: inherit
