permissions:
  contents: write
  id-token: write

on:
  workflow_call:
    inputs:
      passed-dev-tag:
        type: string
        description: Dev tag to fast forward the stage branch to
        required: true
      jf-bundle-version:
        type: string
        description: ''
        required: true

jobs:
  ff-stage-to-dev-tag:
    name: Fast forward stage branch to the dev tag that passed stage testing
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      ref_to_merge: ${{ inputs.passed-dev-tag }}
      base_branch: ${{ vars.STAGE_BRANCH_NAME }}
    secrets: inherit
    permissions:
      contents: write

  promote-release-bundle-to-test:
    needs: [
      ff-stage-to-dev-tag,
    ]
    uses: ./.github/workflows/promote-release-bundle.yml
    with:
      jfrog-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      release-bundle-name: ${{ vars.JFROG_RELEASE_BUNDLE_NAME }}
      release-bundle-version: ${{ inputs.jf-bundle-version }}
      new-environment: TEST
    permissions:
      id-token: write
