on:
  workflow_call:
    inputs:
      platform-tag:
        type: string
        required: false
        default: ""
        description: "Used to set *-runner-os-from-platform-tag-input outputs. If this is unset, ignore those outputs"
    outputs:
      # For build-wheels.yml
      build-runner-os-from-platform-tag-input:
        value: ${{ jobs.get-build-metadata.outputs.build-runner-os-from-platform-tag-input }}
      test-runner-os-from-platform-tag-input:
        value: ${{ jobs.get-build-metadata.outputs.test-runner-os-from-platform-tag-input }}
      # For build-artifacts.yml
      all-python-versions:
        value: ${{ jobs.get-build-metadata.outputs.all-python-versions }}

permissions:
  contents: read

# Maps don't exist in Github Actions, so we have to store the map using a file and fetch it in a job
# This uses up more billing minutes (rounded up to 1 minute for each job run),
# but this should be ok based on the minutes usage data for the aerospike organization
jobs:
  get-build-metadata:
    outputs:
      # Used by both dev and build-and-test-wheel workflow
      all-python-versions: ${{ steps.get-all-python-versions.outputs.python_versions }}
    runs-on: ubuntu-24.04
    env:
      BUILD_METADATA_PATH: .github/workflows/prod-wheel-matrix.json
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - id: get-runner-os-from-platform-tag-input
      if: ${{ inputs.platform-tag != '' }}
      run: |
        # Get runner OS for just one platform tag (i.e when building for one platform on a feature branch)
        echo build_runner_os=$(cat $BUILD_METADATA_PATH | jq -r --arg platform_tag "$platform_tag" '.["platform-tag-to-build-runner-os"].[$platform_tag]') >> $GITHUB_OUTPUT
        echo test_runner_os=$(cat $BUILD_METADATA_PATH | jq --arg platform_tag "$platform_tag" '.["platform-tag-to-test-runner-os"].[$platform_tag]') >> $GITHUB_OUTPUT
      env:
        platform_tag: ${{ inputs.platform-tag }}

    - id: get-all-python-versions
      run: echo python_versions=$(cat $BUILD_METADATA_PATH | jq '.["python-versions"]') >> $GITHUB_OUTPUT
