permissions:
  contents: read

env:
  LOWEST_SUPPORTED_PY_VERSION: '3.10'

on:
  push:
    branches:
    - "dev*"
    - "stage*"
    - "master*"
    - "v*-backport*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: recursive
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ env.LOWEST_SUPPORTED_PY_VERSION }}
        architecture: 'x64'
    - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
