permissions:
  contents: read

env:
  LOWEST_SUPPORTED_PY_VERSION: '3.10'

on:
  push:
    branches:
    - "dev*"
    - "stage*"
    - "master*"
    - "v*-backport*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ env.LOWEST_SUPPORTED_PY_VERSION }}
        architecture: 'x64'
    - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
