name: Build on MacOS

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Docker
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
        sudo install minikube-darwin-amd64 /usr/local/bin/minikube
        minikube start
        shopt -s expand_aliases
        alias kubectl="minikube kubectl --"
    - name: Set up Aerospike Database
      run: |
        kubectl create deployment aerospike --image=aerospike/aerospike-server
        kubectl expose deployment aerospike --type=NodePort --port=3000
    - name: Build
      run: |
        export SSL_LIB_PATH="/usr/local/opt/openssl@1.1/lib/"
        export CPATH="/usr/local/opt/openssl@1.1/include/"
        export STATIC_SSL=1

        python3 setup.py build --force
        python3 setup.py install --force
    - name: Integration tests
      run: |
        # Wait until server is fully spun up
        sleep 3
        cd test/
        python3 -m pip install -r requirements.txt
        ./run
