name: Build on MacOS

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Build
      run: |
        export SSL_LIB_PATH="/usr/local/opt/openssl@1.1/lib/"
        export CPATH="/usr/local/opt/openssl@1.1/include/"
        export STATIC_SSL=1

        python3 setup.py build --force
        python3 setup.py install --force
    - name: Run Aerospike server
      run: |
        # Setup VM
        vagrant init ubuntu/focal64
        vagrant up
        # Setup Aerospike in VM
        commands="wget -O aerospike.tgz https://download.aerospike.com/artifacts/aerospike-server-community/6.1.0.1/aerospike-server-community-6.1.0.1-ubuntu20.04.tgz; \
        tar -xvf aerospike.tgz; \
        cd aerospike-server-community-6.1.0.1-ubuntu20.04/; \
        sudo ./asinstall; \
        sudo systemctl start aerospike; \
        logout;"
        vagrant ssh -c "$commands"
    - name: Run tests
      run: |
        # Wait until server is fully spun up
        sleep 3
        cd test/
        python3 -m pip install -r requirements.txt
        python3 -m pytest new_tests/
