name: Build on MacOS

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        export SSL_LIB_PATH="/usr/local/opt/openssl@1.1/lib/"
        export CPATH="/usr/local/opt/openssl@1.1/include/"
        export STATIC_SSL=1

        python3 setup.py build --force
        python3 setup.py install --force
    - name: Integration tests
        cd test/
        python3 -m pip install -r requirements.txt
        ./run
