name: Build on MacOS

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Build
      run: |
        export SSL_LIB_PATH="/usr/local/opt/openssl@1.1/lib/"
        export CPATH="/usr/local/opt/openssl@1.1/include/"
        export STATIC_SSL=1
        python3 setup.py build --force
        python3 setup.py install --force
    - name: Cache Vagrant image
      id: cache-vagrant-image
      uses: actions/cache@v3
      with:
        path: aerospike-server-ce-ubuntu-bionic.box
        key: vagrant-image
    - name: Use existing Vagrant image for Aerospike server
      if: steps.cache-vagrant-image.outputs.cache-hit != 'true'
      run: |
        vagrant box add aerospike-server-ce-ubuntu-bionic aerospike-server-ce-ubuntu-bionic.box
        vagrant init
        vagrant up
    - name: Create Vagrant image with Aerospike server
      run: |
        vagrant up
        # Wait for server to start
        sleep 3
        vagrant package --output aerospike-server-ce-ubuntu-bionic.box
    - name: Run tests
      run: |
        cd test/
        python3 -m pip install -r requirements.txt
        python3 -m pytest new_tests/
