name: Build on MacOS

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Build
      run: |
        export SSL_LIB_PATH="/usr/local/opt/openssl@1.1/lib/"
        export CPATH="/usr/local/opt/openssl@1.1/include/"
        export STATIC_SSL=1

        python3 setup.py build --force
        python3 setup.py install --force
    - name: Set up Aerospike Database
      run: |
        brew install docker
        docker pull aerospike/aerospike-server
        docker run --name aerospike -d -p 3000:3000 aerospike/aerospike-server
    - name: Integration tests
      run: |
        cd test/
        python3 -m pip install -r requirements.txt
        ./run
