name: Bump version, build wheels, and upload RCs to JFrog

on:
  pull_request_target:
    types:
    - closed
    branches:
    - 'dev*'

jobs:
  test-latest-server-release:
    name: Build, install, and test artifacts against latest server release
    uses: ./.github/workflows/build-wheels.yml
    with:
      run_tests: true
    secrets: inherit

  bump-dev-number:
    if: ${{ !cancelled() }}
    needs: test-latest-server-release
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
    secrets: inherit

  rebuild-artifacts-with-new-dev-num:
    needs: bump-dev-number
    name: Build, install, and test artifacts against latest server release
    uses: ./.github/workflows/build-wheels.yml
    with:
      run_tests: false
      rebuilding-passing-artifacts: true
    secrets: inherit

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    if: ${{ !cancelled() }}
    needs: [
      bump-dev-number,
      rebuild-artifacts-with-new-dev-num
    ]
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets: inherit

  test-artifacts-with-server-rc:
    if: ${{ !cancelled() }}
    needs: [
      upload-to-jfrog,
      bump-dev-number
    ]
    uses: ./.github/workflows/test-server-rc.yml
    with:
      build-number: ${{ needs.bump-dev-number.outputs.new_version }}
      commit_sha: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets: inherit
