name: Dev tests

on:
  push:
    branches:
    - 'dev*'

# 1. When a PR is marked as ready for review, run tests
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a new commit is pushed to `dev`, bump version number in `dev` (this can be disabled manually)

jobs:
  bump-dev-number:
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
    secrets: inherit

  rebuild-artifacts-with-new-dev-num:
    needs: bump-dev-number
    name: Rebuild artifacts with new dev number
    uses: ./.github/workflows/build-wheels.yml
    with:
      run_tests: false
    secrets: inherit

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    needs: [
      bump-dev-number,
      rebuild-artifacts-with-new-dev-num
    ]
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets: inherit
