name: Bump version, build wheels, and upload RCs to JFrog

on:
  pull_request_target:
    types:
    - closed
    branches:
    - 'dev'

jobs:
  bump-dev-number:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
    secrets:
      CLIENT_BOT_PAT: ${{ secrets.CLIENT_BOT_PAT }}

  test-latest-server-release:
    name: Build, install, and test artifacts against latest server release
    needs: bump-dev-number
    uses: ./.github/workflows/build-wheels.yml
    with:
      commit_sha: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets:
      DOCKER_HUB_BOT_USERNAME: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
      DOCKER_HUB_BOT_PW: ${{ secrets.DOCKER_HUB_BOT_PW }}
      MAC_M1_SELF_HOSTED_RUNNER_PW: ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    if: ${{ !cancelled() }}
    needs: [
      test-latest-server-release,
      bump-dev-number
    ]
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets:
      JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

  test-artifacts-with-server-rc:
    if: ${{ !cancelled() }}
    needs: [
      upload-to-jfrog,
      bump-dev-number
    ]
    uses: ./.github/workflows/test-server-rc.yml
    with:
      build-number: ${{ needs.bump-dev-number.outputs.new_version }}
      commit_sha: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets:
      JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
      DOCKER_HUB_BOT_USERNAME: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
      DOCKER_HUB_BOT_PW: ${{ secrets.DOCKER_HUB_BOT_PW }}
      MAC_M1_SELF_HOSTED_RUNNER_PW: ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
