name: Bump version, build wheels, and upload RCs to JFrog

on:
  pull_request_target:
    types:
    - closed
    branches:
    - 'dev'
  workflow_dispatch:
    inputs:
      # Disable this to skip testing the wheel right after building it
      # This is useful if we need to debug later parts of the pipeline
      run_server_release_tests:
        description: "Run server release tests"
        required: true
        type: boolean
        default: true
      # Override the default server version to test against
      # This is helpful if you need to create a backport from an older client major version
      # And that older client major version does not accomodate for breaking changes in the latest server version
      server-release-tag:
        required: true
        default: 'latest'
        description: 'Server release docker image tag'
      # In case the latest server RC is faulty for some reason
      server-rc-tag:
        required: true
        default: 'latest'
        description: 'Server RC docker image tag'

jobs:
  bump-dev-number:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'bump-dev-num'
    secrets:
      CLIENT_BOT_PAT: ${{ secrets.CLIENT_BOT_PAT }}

  test-latest-server-release:
    name: Build, install, and test artifacts against latest server release
    needs: bump-dev-number
    uses: ./.github/workflows/build-wheels.yml
    with:
      server-tag: ${{ github.event == 'workflow_dispatch' && inputs.server-release-tag || 'latest' }}
      run_tests: ${{ github.event == 'workflow_dispatch' && inputs.run_server_release_tests || true }}
      commit_sha: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets:
      DOCKER_HUB_BOT_USERNAME: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
      DOCKER_HUB_BOT_PW: ${{ secrets.DOCKER_HUB_BOT_PW }}
      MAC_M1_SELF_HOSTED_RUNNER_PW: ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    if: ${{ !cancelled() }}
    needs: [
      test-latest-server-release,
      bump-dev-number
    ]
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets:
      JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

  test-artifacts-with-server-rc:
    if: ${{ !cancelled() }}
    needs: [
      upload-to-jfrog,
      bump-dev-number
    ]
    uses: ./.github/workflows/test-server-rc.yml
    with:
      server-tag: ${{ github.event == 'workflow_dispatch' && inputs.server-rc-tag || 'latest' }}
      build-number: ${{ needs.bump-dev-number.outputs.new_version }}
      commit_sha: ${{ needs.bump-dev-number.outputs.bump_sha }}
    secrets:
      JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
      DOCKER_HUB_BOT_USERNAME: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
      DOCKER_HUB_BOT_PW: ${{ secrets.DOCKER_HUB_BOT_PW }}
      MAC_M1_SELF_HOSTED_RUNNER_PW: ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
