name: Stage tests

on:
  push:
    branches:
    - 'stage'
  workflow_dispatch:
    inputs:
      # For creating a backport client version
      server-tag:
        required: true
        default: 'latest'
        description: 'Server docker image tag'

jobs:
  promote-dev-build-to-rc:
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'promote-dev-build-to-rc'
    secrets:
      CLIENT_BOT_PAT: ${{ secrets.CLIENT_BOT_PAT }}

  run-stage-tests:
    uses: ./.github/workflows/stage-tests.yml
    with:
      commit_sha: ${{ jobs.promote-dev-build-to-rc.outputs.bump_sha }}
