name: Build and upload release artifacts to JFrog
on:
  workflow_dispatch:

jobs:
  promote-rc-build-to-release:
    uses: ./.github/workflows/bump-version.yml
    with:
      change: promote-rc-build-to-release

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    needs: promote-rc-build-to-release
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      new_version: ${{ needs.promote-rc-build-to-release.outputs.new_version }}
    secrets:
      JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
