name: Run dev tests and promote release bundle to DEV
run-name: Run dev tests and promote release bundle to DEV (dry-run=${{ inputs.dry-run }}, test-file=${{ inputs.test-file }})

permissions:
  # We are building the artifacts in build-artifacts.yml
  contents: read
  # For shared reusable workflows
  # TODO: look into more
  id-token: write
  statuses: write
  # For downloading docker images from ghcr.io
  packages: read

on:
  workflow_dispatch:
    inputs:
      # These inputs are in case we need to test against a server RC
      registry-name:
        type: string
        required: true
        description: Registry name
        default: 'docker.io'
      image-name:
        type: string
        required: true
        description: Image name
        default: 'aerospike/aerospike-server-enterprise'
      server-tag:
        type: string
        required: true
        default: 'latest'
        description: 'Server docker image tag (e.g to test a client backport version)'
      # For testing purposes
      dry-run:
        required: false
        default: false
        type: boolean
        description: Don't create release bundle
      run_tests:
        required: false
        default: false
        type: boolean
        description: Run dev tests
      test-file:
        required: false
        type: string
        description: For speeding up debugging
      build-type:
        required: false
        default: 'release'
        type: string
        description: Build metadata
jobs:
  build-test-and-publish-artifacts-as-jfrog-build:
    strategy:
      matrix:
    uses: aerospike/shared-workflows/.github/workflows/reusable_artifacts-cicd.yaml@7f563f650178064e0c0cedde00277226bfb131de
    with:
      gh-artifact-directory: dist
      gh-workflows-ref: 7f563f650178064e0c0cedde00277226bfb131de
      jf-build-name: ${{ vars.JFROG_BUILD_NAME }}
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      # TODO: maybe this should be the actions run #?
      version: ${{ github.ref_name }}
      build-script-path: ./build-python-client.sh
      dry-run: ${{ inputs.dry-run }}
      build-type: ${{ inputs.build-type }}
      # TODO: maybe don't need platform tag anymore if we build from a script instead of
      # cibuildwheel
      matrix-json: |
        {"include":[
          {"runs-on":"ubuntu-22.04","platform-tag":"manylinux_x86_64"},
          {"runs-on":"ubuntu-22.04-arm","platform-tag":"manylinux_aarch64"},
          {"runs-on":"macos-14-large","platform-tag":"macosx_x86_64"},
          {"runs-on":"macos-14","platform-tag":"macosx_arm64"},
          {"runs-on":"windows-2022","platform-tag":"win_amd64"},
        ]}
      setup-python: true

    secrets: inherit

  create-release-bundle-and-promote-to-dev:
    if: ${{ inputs.dry-run }}
    needs: build-test-and-publish-artifacts-as-jfrog-build
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@7f563f650178064e0c0cedde00277226bfb131de
    with:
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      jf-build-names: ${{ vars.JFROG_BUILD_NAME }}
      jf-bundle-name: ${{ vars.JFROG_BUILD_NAME }}
      version: ${{ github.ref_name }}
      gh-workflows-ref: 7f563f650178064e0c0cedde00277226bfb131de # Should match the version in your 'uses:' line
