name: Run dev tests and promote release bundle to DEV
run-name: Run dev tests and promote release bundle to DEV (dry-run=${{ inputs.dry-run }}, test-file=${{ inputs.test-file }})

permissions:
  # We are building the artifacts in build-artifacts.yml
  contents: read
  # For shared reusable workflows
  id-token: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      # These inputs are in case we need to test against a server RC
      registry-name:
        type: string
        required: true
        description: Registry name
        default: 'docker.io'
      image-name:
        type: string
        required: true
        description: Image name
        default: 'aerospike/aerospike-server-enterprise'
      server-tag:
        type: string
        required: true
        default: 'latest'
        description: 'Server docker image tag (e.g to test a client backport version)'
      # For testing purposes
      dry-run:
        required: false
        default: false
        type: boolean
        description: Don't create release bundle
      run_tests:
        required: false
        default: false
        type: boolean
        description: Run dev tests
      test-file:
        required: false
        type: string
        description: For speeding up debugging
      build-type:
        required: false
        default: 'release'
        type: string
        description: Build metadata
jobs:
  get-runner-os-and-all-supported-python-versions:
    uses: ./.github/workflows/get-runner-os-and-all-supported-python-versions.yml
    with:
      platform-tag: '*'

  get-next-release-version-and-latest-tag:
    outputs:
      next-release-version: ${{ steps.get-next-release-version.outputs.next_release_version }}
      latest-tag: ${{ steps.get-latest-tag.outputs.latest_tag }}
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0

    - name: Install library that parses PEP 440 versions
      run: pip install parver -c requirements.txt
      working-directory: .github/workflows

    - id: get-next-release-version
      run: echo next_release_version=$(cat VERSION) >> $GITHUB_OUTPUT

    - id: get-latest-tag
      run: |
        latest_tag=$(git describe --tags --exact-match $prev_commit)
        if [[ "$latest_tag" == "$next_release_version" ]]; then
          echo "We have not merged any changes to dev since the last release yet." >&2
          exit 1
        fi
        echo latest_tag=$latest_tag >> $GITHUB_OUTPUT

  build-test-and-publish-artifacts-as-jfrog-build:
    needs: [
      get-runner-os-and-all-supported-python-versions,
      get-next-release-version-and-latest-tag
    ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_artifacts-cicd.yaml@7f563f650178064e0c0cedde00277226bfb131de
    with:
      gh-artifact-directory: wheelhouse
      gh-workflows-ref: 7f563f650178064e0c0cedde00277226bfb131de
      jf-build-name: ${{ vars.JFROG_BUILD_NAME }}
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      # This workflow generates a unique build id internally
      version: ${{ needs.get-next-release-version-and-latest-tag.outputs.next-release-version }}
      build-script-path: ./build-prod-wheel.bash
      matrix-json: >-
        {
          "runs-on": ${{ needs.get-runner-os-and-all-supported-python-versions.outputs.runner-oses }},
          "python-version": ${{ needs.get-runner-os-and-all-supported-python-versions.outputs.python-versions }}
        }
      dry-run: ${{ inputs.dry-run }}
      build-type: ${{ inputs.build-type }}
      setup-python: true
      build-env: MANYLINUX_REGISTRY_NAME=${{ vars.JF_EXTERNAL_URL }}/${{ vars.JFROG_REPO_FOR_CUSTOM_MANYLINUX_IMAGES }}
    secrets:
      gpg-private-key: ''
      gpg-public-key: ''
      gpg-key-pass: ''

  create-release-bundle-and-promote-to-dev:
    if: ${{ inputs.dry-run }}
    needs: [
      build-test-and-publish-artifacts-as-jfrog-build,
      get-next-release-version-and-latest-tag
    ]
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@7f563f650178064e0c0cedde00277226bfb131de
    with:
      jf-project: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      jf-build-names: ${{ vars.JFROG_BUILD_NAME }}
      jf-bundle-name: ${{ vars.JFROG_BUILD_NAME }}
      # JFrog release bundle version
      version: ${{ needs.get-next-release-version-and-latest-tag.outputs.latest-tag }}
      gh-workflows-ref: 7f563f650178064e0c0cedde00277226bfb131de # Should match the version in your 'uses:' line
