on:
  workflow_call:
    inputs:
      dev-tag-to-test:
        type: string
        required: true
    secrets:
      JFROG_PLATFORM_URL:
        required: true
      JFROG_ACCESS_TOKEN:
        required: true

jobs:
  upload-jfrog-artifacts-as-github-artifacts:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./.github/actions/download-jf-builds
          ./.github/workflows/upload-jfrog-artifacts-to-github.js

    - name: Download JFrog builds for this dev version
      uses: ./.github/actions/download-jf-builds
      with:
        build-version: ${{ inputs.dev-tag-to-test }}
        jfrog-platform-url: ${{ secrets.JFROG_PLATFORM_URL }}
        jfrog-access-token: ${{ secrets.JFROG_ACCESS_TOKEN }}
        jfrog-repo-name: ${{ vars.JFROG_REPO_NAME }}

    - run: npm i @actions/artifact

    - name: Upload builds to Github as artifacts
      # TODO: need to check this works
      uses: actions/github-script@v7
      with:
        script: |
          const module = require('./.github/workflows/upload-jfrog-artifacts-to-github.js')
          module.upload_jfrog_artifacts_to_github(${{ inputs.dev-tag-to-test }})
        result-encoding: string

  run-stage-tests:
    needs: upload-jfrog-artifacts-as-github-artifacts
    uses: ./.github/workflows/stage-tests.yml
    secrets: inherit
    with:
      ref: ${{ inputs.dev-tag-to-test }}
