name: Dev to stage

permissions:
  contents: write
  id-token: write
  statuses: write

on:
  # This workflow manipulates the stage and dev branches regardless of the branch this workflow is run from
  workflow_dispatch:
    inputs:
      server-tag:
        required: true
        description: 'Server docker image tag'
      test-file:
        required: false
        default: ''
        description: 'new_tests/<value>'

jobs:
  # We want to skip the stage tests if the changes made between dev and stage wouldn't affect the results of the stage tests
  # TODO: update whitelisted changes
  compare-latest-dev-tag-and-stage:
    outputs:
      # This is always available, but the stage tests only use it if they're being run (i.e not skipped)
      latest-dev-tag: ${{ steps.get-dev-tag.outputs.latest-dev-tag }}
      run_stage_tests: ${{ steps.run_stage_tests.outputs.run_stage_tests }}
    runs-on: ubuntu-22.04
    env:
      DEV_BRANCH_NAME: ${{ vars.DEV_BRANCH_NAME }}
      STAGE_BRANCH_NAME: ${{ vars.STAGE_BRANCH_NAME }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        # Get all tags
        fetch-depth: 0

    - name: Get latest dev tag
      run: echo latest-dev-tag=$(git describe --tags --abbrev=0 origin/$DEV_BRANCH_NAME) >> $GITHUB_OUTPUT
      id: get-dev-tag

    - name: Get number of files that were changed between dev and stage (with some exceptions)
      run: |
        num_files_changed=$(git diff origin/$STAGE_BRANCH_NAME..origin/$DEV_BRANCH_NAME --name-only | grep --invert-match --count -e "^doc/" -e "^aerospike-stubs/" -e VERSION || true)
        echo NUM_FILES_CHANGED=$num_files_changed >> $GITHUB_ENV
      # We want this step to fail if a command failed while using pipes
      shell: bash

    - name: If any files were changed besides the exceptions, run the stage tests
      run: echo run_stage_tests=${{ env.NUM_FILES_CHANGED != '0' }} >> $GITHUB_OUTPUT
      id: run_stage_tests

  reupload-jfrog-artifacts-as-github-ones:
    needs: compare-latest-dev-tag-and-stage
    if: ${{ needs.compare-latest-dev-tag-and-stage.outputs.run_stage_tests == 'true' }}
    runs-on: ubuntu-24.04
    outputs:
      build_number: ${{ steps.get-jf-build-id.outputs.build_number }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: step-security/setup-jfrog-cli@3054b554c0fb4915b3d58847fb7730c593dbb934 # v5.0.0
      env:
        JF_URL: https://${{ vars.JF_EXTERNAL_URL }}
        JF_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      with:
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}

    - name: Get workflow code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Expose GitHub Runtime
      uses: step-security/ghaction-github-runtime@3ec2bea23280fd469bb5d759888e9701173b2b0f # v4.0.0

    - name: Download JFrog artifacts from release bundle and reupload as Github artifacts
      id: get-jf-build-id
      run: |
        export JFROG_CLI_LOG_LEVEL=DEBUG
        # Note that setting JF_PROJECT from above step doesn't apply to this command for some reason
        build_number=$(jf rbs --project "$JFROG_PROJECT" --format json --order-by created versions "$JFROG_RELEASE_BUNDLE_NAME" | jq -r '.release_bundles[0].release_bundle_version')
        echo build_number="$build_number" >> $GITHUB_OUTPUT

        # Currently no way to download specific artifacts from a release bundle
        # Using ARTIFACT_FILE_NAME_PATTERN with jf rt dl --bundle doesn't work
        DEST_DIR_PATH="./dest-dir/"
        jf rt dl --fail-no-op --build="${JFROG_BUILD_NAME}/${build_number}" --flat "${JFROG_PROJECT}-pypi-dev-local/**/*" "$DEST_DIR_PATH"

        npm install
        node upload-individual-github-artifacts.js "$DEST_DIR_PATH" "$GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS"
      shell: bash -ex {0}
      working-directory: .github/workflows
      env:
        JFROG_RELEASE_BUNDLE_NAME: ${{ vars.JFROG_RELEASE_BUNDLE_NAME }}
        JFROG_BUILD_NAME: ${{ vars.JFROG_BUILD_NAME }}
        JFROG_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
        GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS: ${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}

  run-stage-tests:
    needs: reupload-jfrog-artifacts-as-github-ones
    if: ${{ !cancelled() && needs.reupload-jfrog-artifacts-as-github-ones.result == 'success' }}
    uses: ./.github/workflows/stage-tests.yml
    # Need to pass in JFrog secrets
    secrets: inherit
    with:
      # TODO: more work to get this dynamically
      macos-python-versions-to-test: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      server-tag: ${{ inputs.server-tag }}
      test-file: ${{ inputs.test-file }}
      run-integration-tests-on-macos-x86: false

  # Stage tests have passed or skipped
  # so it is safe to update the stage branch with the changes in dev, promote the version to an RC, and rebuild and upload the RC to JFrog
  # We store the subsequent jobs after the stage tests in a separate reusable workflow...
  # because if stage tests were skipped, all subsequent jobs will be skipped by default too (both direct and indirect descendents)
  # This means we have to add a manual check for each subsequent job that checks if the stage tests were skipped in order to run them
  # It's easier to just add this manual check once to a reusable workflow that wraps around all the subsequent jobs
  fast-forward-stage-to-dev-and-promote-rb-to-test:
    needs: [
      compare-latest-dev-tag-and-stage,
      reupload-jfrog-artifacts-as-github-ones,
      run-stage-tests
    ]
    if: ${{ !cancelled() && needs.compare-latest-dev-tag-and-stage.result == 'success' && ((needs.reupload-jfrog-artifacts-as-github-ones.result == 'success' && needs.run-stage-tests.result == 'success') || (needs.reupload-jfrog-artifacts-as-github-ones.result == 'skipped' && needs.run-stage-tests.result == 'skipped')) }}
    uses: ./.github/workflows/ff-stage-and-promote-release-bundle-to-test.yml
    with:
      passed-dev-tag: ${{ needs.compare-latest-dev-tag-and-stage.outputs.latest-dev-tag }}
      jf-bundle-version: ${{ needs.reupload-jfrog-artifacts-as-github-ones.outputs.build_number }}
    secrets: inherit
