name: Stage to master
on:
  workflow_dispatch:

jobs:
  ff-master-to-stage:
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      ref_to_merge: origin/${{ vars.STAGE_BRANCH_NAME }}
      base_branch: ${{ vars.MASTER_BRANCH_NAME }}
    secrets: inherit

  promote-rc-build-to-release:
    needs: ff-master-to-stage
    uses: ./.github/workflows/apply-change-to-version-and-tag-latest-commit.yml
    with:
      change: strip_prerelease_part
      ref: ${{ vars.MASTER_BRANCH_NAME }}
    secrets: inherit
