name: Stage tests

# Downloads artifacts either from Github or JFrog
# and runs category 1 (source distribution) and category 2 (binary distribution) tests
# The purpose is to test that our artifacts work on the Linux distros / OS versions that the client supports
# and QE doesn't have enough disk space for more Linux distros, so we have some tests here in Github Actions

permissions:
  contents: read
  id-token: write
  statuses: write

on:
  workflow_call:
    inputs:
      macos-python-versions-to-test:
        required: true
        type: string
      server-tag:
        type: string
        required: true
        description: 'Server docker image tag'
      test-file:
        required: false
        default: ''
        type: string
        description: 'new_tests/<value>'
      # Set to false by the upstream stage workflow
      run-integration-tests-on-macos-x86:
        required: false
        type: boolean
        default: false

jobs:
  linux-distro-tests:
    strategy:
      matrix:
        test-case: [
          # Docker image + tag, Docker image platform (cpu arch), Python version, build-from-source
          ["amazonlinux:2023", "x86_64", "3.11", false],
          ["amazonlinux:2023", "aarch64", "3.11", false],

          ["ubuntu:22.04", "x86_64", "3.10", false],
          ["ubuntu:22.04", "aarch64", "3.10", false],
          ["ubuntu:24.04", "x86_64", "3.12", false],
          ["ubuntu:24.04", "aarch64", "3.12", false],

          # Bookworm is Debian 12
          ["python:3.10-bookworm", "x86_64", "3.10", false],
          ["python:3.10-bookworm", "aarch64", "3.10", false],
          ["python:3.11-bookworm", "x86_64", "3.11", false],
          ["python:3.11-bookworm", "aarch64", "3.11", false],
          ["python:3.12-bookworm", "x86_64", "3.12", false],
          ["python:3.12-bookworm", "aarch64", "3.12", false],
          ["python:3.13-bookworm", "x86_64", "3.13", false],
          ["python:3.13-bookworm", "aarch64", "3.13", false],
          ["python:3.14-rc-bookworm", "x86_64", "3.14", false],
          ["python:3.14-rc-bookworm", "aarch64", "3.14", false],
          # QE currently covers Debian 13 on all client-supported Python versions
          # We do not use ubi9/python-311 because we cannot install packages using dnf as root
          ["redhat/ubi9", "x86_64", "3.11", false],
          ["redhat/ubi9", "aarch64", "3.11", false],

          ["amazonlinux:2023", "x86_64", "3.11", true],
          ["redhat/ubi9", "x86_64", "3.11", true],
        ]
      fail-fast: false
    uses: ./.github/workflows/test-in-container.yml
    with:
      container-image-name: ${{ matrix.test-case[0] }}
      cpu-arch: ${{ matrix.test-case[1] }}
      python-version: ${{ matrix.test-case[2] }}
      build-from-source: ${{ matrix.test-case[3] }}
      server-tag: ${{ inputs.server-tag }}
      test-file: ${{ inputs.test-file }}
    secrets: inherit

  macos-and-windows:
    strategy:
      matrix:
        runner-os: [
          macos-15-intel,
          macos-26-intel,
          # These are arm64 runners
          macos-15,
          macos-26,
          windows-2025
        ]
        python-version: ${{ fromJson(inputs.macos-python-versions-to-test) }}
      fail-fast: false
    uses: ./.github/workflows/test-wheel.yml
    with:
      runner-os-json-string: ${{ format('"{0}"', matrix.runner-os) }}
      python-version: ${{ matrix.python-version }}
      server-tag: ${{ inputs.server-tag }}
      run-integration-tests: ${{ endsWith(matrix.runner-os, '-intel') && inputs.run-integration-tests-on-macos-x86 }}
      test-file: ${{ inputs.test-file }}
    secrets: inherit
