name: Dev to stage

permissions:
  contents: write
  id-token: write
  statuses: write

on:
  # This workflow manipulates the stage and dev branches regardless of the branch this workflow is run from
  workflow_dispatch:
    inputs:
      server-tag:
        required: true
        description: 'Server docker image tag'
      test-file:
        required: false
        default: ''
        description: 'new_tests/<value>'

jobs:
  compare-latest-dev-tag-and-stage:
    uses: ./.github/workflows/decide-to-run-integration-tests.yml
    with:
      earlier_rev: origin/${{ vars.STAGE_BRANCH_NAME }}
      later_rev: origin/${{ vars.DEV_BRANCH_NAME }}

  get-release-bundle-version-to-optionally-test-and-promote:
    needs: compare-latest-dev-tag-and-stage
    uses: ./.github/workflows/get-latest-release-bundle.yml
    with:
      expected-release-bundle-tag: ${{ needs.compare-latest-dev-tag-and-stage.outputs.later_rev_tag }}

  # Preliminary step for running the stage tests
  reupload-jfrog-artifacts-as-github-ones:
    needs: [
      compare-latest-dev-tag-and-stage,
      # For pulling the artifacts from the release bundle
      get-release-bundle-version-to-optionally-test-and-promote
    ]
    if: ${{ needs.compare-latest-dev-tag-and-stage.outputs.run_integration_tests == 'true' }}
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - uses: step-security/setup-jfrog-cli@53aeacb709fce45d0baf69a13ec3342f7e2d71a9 # v5.1.0
      env:
        JF_URL: https://${{ vars.JF_EXTERNAL_URL }}
        JF_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      with:
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}

    - name: Get workflow code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        sparse-checkout: |
          .github

    - name: Expose GitHub Runtime
      uses: step-security/ghaction-github-runtime@3ec2bea23280fd469bb5d759888e9701173b2b0f # v4.0.0

    - name: Download JFrog artifacts from release bundle and reupload as Github artifacts
      run: |
        DEST_DIR_PATH="./dest-dir/"
        jf rt dl --project "$JFROG_PROJECT" --fail-no-op --flat --bundle="${JFROG_RELEASE_BUNDLE_NAME}/${JFROG_RELEASE_BUNDLE_VERSION}" '*' "$DEST_DIR_PATH"

        npm install
        node upload-individual-github-artifacts.js "$DEST_DIR_PATH" "$GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS"
      shell: bash -ex {0}
      working-directory: .github/workflows
      env:
        JFROG_RELEASE_BUNDLE_NAME: ${{ vars.JFROG_RELEASE_BUNDLE_NAME }}
        JFROG_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
        GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS: ${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}
        JFROG_RELEASE_BUNDLE_VERSION: ${{ needs.get-release-bundle-version-to-optionally-test-and-promote.outputs.release-bundle-version }}

  run-stage-tests:
    needs: [
      compare-latest-dev-tag-and-stage,
      reupload-jfrog-artifacts-as-github-ones
    ]
    if: |
      !cancelled() &&
      (
        needs.compare-latest-dev-tag-and-stage.outputs.run_integration_tests == 'true'
        &&
        needs.reupload-jfrog-artifacts-as-github-ones.result == 'success'
      )
    uses: ./.github/workflows/stage-tests.yml
    # Need to pass in JFrog secrets
    secrets: inherit
    with:
      # TODO: more work to get this dynamically
      python-versions-to-test: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      # Need to use the same version of tests designed for the client version we're promoting
      rev-of-integration-tests: ${{ needs.compare-latest-dev-tag-and-stage.outputs.later_rev_tag }}
      server-tag: ${{ inputs.server-tag }}
      test-file: ${{ inputs.test-file }}
      run-integration-tests-on-macos-x86: false

  # Stage tests have passed or skipped
  # so it is safe to update the stage branch with the changes in dev and promote the release bundle to TEST
  # We store the subsequent jobs after the stage tests in a separate reusable workflow...
  # because if stage tests were skipped, all subsequent jobs will be skipped by default too (both direct and indirect descendents)
  # This means we have to add a manual check for each subsequent job that checks if the stage tests were skipped in order to run them
  # It's easier to just add this manual check once to a reusable workflow that wraps around all the subsequent jobs
  fast-forward-stage-to-dev-and-promote-rb-to-test:
    needs: [
      compare-latest-dev-tag-and-stage,
      get-release-bundle-version-to-optionally-test-and-promote,
      reupload-jfrog-artifacts-as-github-ones,
      run-stage-tests
    ]
    if: |
      !cancelled() &&
      needs.compare-latest-dev-tag-and-stage.result == 'success' &&
      needs.get-release-bundle-version-to-optionally-test-and-promote.result == 'success' &&
      (
        (needs.reupload-jfrog-artifacts-as-github-ones.result == 'success' && needs.run-stage-tests.result == 'success')
        ||
        (needs.reupload-jfrog-artifacts-as-github-ones.result == 'skipped' && needs.run-stage-tests.result == 'skipped')
      )
    uses: ./.github/workflows/ff-stage-and-promote-release-bundle-to-test.yml
    with:
      # Where to fast forward stage to
      passed-dev-tag: ${{ needs.compare-latest-dev-tag-and-stage.outputs.later_rev_tag }}
      jf-bundle-version: ${{ needs.get-release-bundle-version-to-optionally-test-and-promote.outputs.release-bundle-version }}
    secrets: inherit
