name: Stage to master
on:
  # TODO: cannot be run manually, should be triggered by jfrog
  workflow_dispatch:

jobs:
  ff-master-to-stage:
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      ref_to_merge: origin/${{ vars.STAGE_BRANCH_NAME }}
      base_branch: ${{ vars.MASTER_BRANCH_NAME }}
    secrets: inherit
