name: (Optionally build and) test wheel inside container

on:
  workflow_call:
    inputs:
      container-image-name:
        required: true
        type: string
      cpu-arch:
        required: true
        type: string
      python-version:
        required: true
        type: string
      build-from-source:
        required: true
        default: false
        description: 'If false, download wheel artifact from Github'
        type: boolean
      server-tag:
        required: true
        type: string

jobs:
  test-wheel:
    runs-on: ${{ inputs.cpu-arch == 'aarch64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}
    env:
      CONTAINER_NAME: linux-distro
      REPO_DIR_NAME: aerospike-client-python
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        sparse-checkout: |
          test
          .github

    - run: docker run -d --name "$CONTAINER_NAME" "${{ inputs.container-image-name }}" tail -f /dev/null

    - uses: ./.github/actions/run-ee-server
      with:
        server-tag: ${{ inputs.server-tag }}
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}
        where-is-client-connecting-from: 'separate-docker-container'

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: ${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}-${{ inputs.python-version }}-*manylinux*${{ inputs.cpu-arch }}*
        path: ./

    - name: Copy repo and wheel into container
      run: docker cp ../$REPO_DIR_NAME $CONTAINER_NAME:/

    - name: 'DNF based distros: install python3'
      if: ${{ inputs.container-image-name == 'amazonlinux:2023' || contains(inputs.container-image-name, 'ubi') }}
      run: docker exec "$CONTAINER_NAME" dnf install -y python3.11

    - name: 'Cat 1: Install build dependencies'
      # Here we assume all cat 1 tests are running on a dnf-based. distro
      run: |
        docker exec "$CONTAINER_NAME" dnf install -y libyaml-devel \
          openssl-devel \
          glibc-devel \
          autoconf \
          automake \
          libtool \
          zlib-devel \
          openssl-devel \
          python3.11-devel
        docker exec --workdir /$REPO_DIR_NAME "$CONTAINER_NAME" python${{ inputs.python-version }} -m pip install -r requirements.txt
        docker exec --workdir /$REPO_DIR_NAME "$CONTAINER_NAME" python${{ inputs.python-version }} -m build

    - name: Install wheel
      run: docker exec --workdir /$REPO_DIR_NAME "$CONTAINER_NAME" python${{ inputs.python-version }} -m pip install *.whl

    - name: Install test prerequisites
      run: docker exec --workdir /$REPO_DIR_NAME/test "$CONTAINER_NAME" python${{ inputs.python-version }} -m pip install -r requirements.txt

    - name: Run tests
      run: docker exec --workdir /$REPO_DIR_NAME/test "$CONTAINER_NAME" python${{ inputs.python-version }} -m pytest new_tests/

    - if: ${{ always() }}
      run: docker logs aerospike
