name: (Optionally build and) test wheel inside container

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      container-image-name:
        required: true
        type: string
      cpu-arch:
        required: true
        type: string
      python-version:
        required: true
        type: string
      build-from-source:
        required: false
        default: false
        description: 'If false, download wheel artifact from Github'
        type: boolean
      test-file:
        required: false
        type: string
        description: 'Only used if running integration tests'
      server-tag:
        required: true
        type: string

jobs:
  test-in-container:
    runs-on: ${{ inputs.cpu-arch == 'x86_64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}
    env:
      LINUX_DISTRO_IMAGE_NAME: ${{ inputs.container-image-name }}
      CONTAINER_NAME: linux-distro
      REPO_DIR_NAME: aerospike-client-python
      PYTHON_VERSION: ${{ inputs.python-version }}
      PIP_INSTALL_COMMAND: 'pip install'
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        sparse-checkout: |
          test
          .github

    - if: ${{ contains(inputs.container-image-name, vars.JF_EXTERNAL_URL) }}
      name: Log into JFrog to pull custom manylinux image
      id: setup-jf
      uses: jfrog/setup-jfrog-cli@1641575d87647fb969c0545f0b6a76873e328b7c # v5.0.0
      env:
        JF_URL: https://${{ vars.JF_EXTERNAL_URL }}
        JF_PROJECT: ${{ vars.JFROG_PROJECT_FOR_CLIENT_TEAM }}
      with:
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}

    - if: ${{ contains(inputs.container-image-name, vars.JF_EXTERNAL_URL) }}
      name: Log into internal JFrog Docker registry
      uses: docker/login-action@v4
      with:
        registry: ${{ vars.JF_EXTERNAL_URL }}/${{ vars.JFROG_REPO_FOR_CUSTOM_MANYLINUX_IMAGES }}
        username: ${{ steps.setup-jf.outputs.oidc-user }}
        password: ${{ steps.setup-jf.outputs.oidc-token }}

    - uses: ./.github/actions/run-ee-server
      id: run-ee-server
      with:
        server-tag: ${{ inputs.server-tag }}
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}
        features-content: ${{ secrets.FEATURES_CONTENT }}
        where-is-client-connecting-from: 'separate-docker-container'

    - run: docker run -d --network "${{ steps.run-ee-server.outputs.container-network }}" -v /:/host:ro --name "$CONTAINER_NAME" "$LINUX_DISTRO_IMAGE_NAME" tail -f /dev/null

    - if: ${{ inputs.build-from-source }}
      run: |
        echo ARTIFACT_NAME_PATTERN=${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}-sdist >> $GITHUB_ENV
        echo FILE_PATTERN_TO_INSTALL=*.tar.gz >> $GITHUB_ENV

    - if: ${{ !inputs.build-from-source }}
      run: |
        echo ARTIFACT_NAME_PATTERN=${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}-${{ inputs.python-version }}-*manylinux*${{ inputs.cpu-arch }}* >> $GITHUB_ENV
        echo FILE_PATTERN_TO_INSTALL=*.whl >> $GITHUB_ENV

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: ${{ env.ARTIFACT_NAME_PATTERN }}
        path: ./

    - name: Copy repo and artifact into container
      run: docker cp ../$REPO_DIR_NAME $CONTAINER_NAME:/

    - name: 'DNF based distros: install python3'
      if: ${{ inputs.container-image-name == 'amazonlinux:2023' || contains(inputs.container-image-name, 'ubi') }}
      run: docker exec "$CONTAINER_NAME" dnf install -y python3.11

    - name: 'Ubuntu: Install python 3 that comes by default (step 1)'
      if: ${{ startsWith(env.LINUX_DISTRO_IMAGE_NAME, 'ubuntu') }}
      run: |
        docker exec "$CONTAINER_NAME" apt-get update
        docker exec "$CONTAINER_NAME" apt-get install python3 python3-pip -y

    - name: Make sure pip is installed
      # This is good to check in general, so we run for all distros
      # Ubuntu doesn't have this by default though, but it's fine since it has pip already
      if: ${{ !startsWith(env.LINUX_DISTRO_IMAGE_NAME, 'ubuntu') }}
      run: docker exec "$CONTAINER_NAME" "python${PYTHON_VERSION}" -m ensurepip

    - if: ${{ env.LINUX_DISTRO_IMAGE_NAME == 'ubuntu:24.04' }}
      # Python 3.12+ fails to install packages to the system directory by default
      run: echo PIP_INSTALL_COMMAND="$PIP_INSTALL_COMMAND --break-system-packages" >> $GITHUB_ENV

    - name: 'Cat 1: build from source'
      if: ${{ inputs.build-from-source }}
      # Here we assume all cat 1 tests are running on a dnf-based distro
      run: |
        docker exec "$CONTAINER_NAME" dnf install -y libyaml-devel \
          openssl-devel \
          glibc-devel \
          autoconf \
          automake \
          libtool \
          zlib-devel \
          openssl-devel \
          python3.11-devel

    - name: Install wheel
      run: docker exec --workdir /$REPO_DIR_NAME "$CONTAINER_NAME" "python${PYTHON_VERSION}" -m $PIP_INSTALL_COMMAND $FILE_PATTERN_TO_INSTALL

    - name: Install test prerequisites
      run: docker exec --workdir /$REPO_DIR_NAME/test "$CONTAINER_NAME" "python${PYTHON_VERSION}" -m $PIP_INSTALL_COMMAND -r requirements.txt

    - name: Run tests
      run: docker exec --workdir /$REPO_DIR_NAME/test "$CONTAINER_NAME" "python${PYTHON_VERSION}" -m pytest new_tests/$TEST_FILE
      env:
        TEST_FILE: ${{ inputs.test-file }}

    - if: ${{ always() && steps.run-ee-server.conclusion == 'success' }}
      run: docker logs ${{ steps.run-ee-server.outputs.container-name }}
