on:
  workflow_call:
    inputs:
      runner-os:
        required: true
        type: string
      # For downloading the correct wheel from upstream jobs
      platform-tag:
        required: true
        type: string
      python-version:
        required: true
        type: string
      # For accessing the QE builds
      registry-name:
        required: true
        type: string
      registry-username:
        required: true
        type: string
      registry-password:
        required: true
        type: string
      image-name:
        required: true
        type: string
      server-tag:
        required: true
        type: string
      test-file:
        required: false
        type: string
        default: ''
    secrets:
      MAC_M1_SELF_HOSTED_RUNNER_PW:
        required: false

jobs:
  test-wheel:
    runs-on: ${{ inputs.runner-os }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Create status check message
      run: echo STATUS_CHECK_MESSAGE="Test wheel (${{ inputs.python-version }}-${{ inputs.platform-tag }})" >> $GITHUB_ENV
      shell: bash

    - name: Show job status for commit
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
      with:
        sha: ${{ github.sha }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}-${{ inputs.python-version }}-${{ inputs.platform-tag }}
        path: ./

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install wheel
      run: pip install *.whl
      shell: bash

    - run: pip install -r requirements.txt
      working-directory: test
      shell: bash

    # Need to be able to save Docker Hub credentials to keychain
    # Unable to do this via the ansible script for self hosted mac m1 runners
    - if: ${{ inputs.platform-tag == 'macosx_arm64' }}
      run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
      shell: bash

    - uses: ./.github/actions/run-ee-server
      with:
        registry-name: ${{ inputs.registry-name }}
        registry-username: ${{ inputs.registry-username }}
        registry-password: ${{ inputs.registry-password }}
        image-name: ${{ inputs.image-name }}
        server-tag: ${{ inputs.server-tag }}
        where-is-client-connecting-from: ${{ inputs.platform-tag == 'win_amd64' && 'remote-connection' || 'docker-host' }}

    - run: python3 -m pytest -vvs --full-trace new_tests/${{ inputs.test-file }}
      working-directory: test
      shell: bash

    - name: Show server logs to debug test results
      if: ${{ !failure() }}
      run: docker logs aerospike
      shell: bash

    - name: Show job status for commit
      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        sha: ${{ github.sha }}
        status: ${{ job.status }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}
