name: 'Test local build'

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      docker-image:
        required: true
        type: string
    secrets:
      DOCKER_HUB_BOT_USERNAME:
        required: true
      DOCKER_HUB_BOT_PW:
        required: true

jobs:
  test-local-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
        architecture: 'x64'

    - uses: actions/download-artifact@v3
      with:
        name: wheel-${{ inputs.python-version }}

    - name: Install client
      run: pip install *.whl

    - name: Install test dependencies
      run: pip install -r test/requirements.txt

    - name: Create config file using template
      run: cp config.conf.template config.conf
      working-directory: test

    - if: ${{ endsWith(inputs.docker-image, '-rc') }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_BOT_PW }}

    - name: Run Aerospike server
      run: docker run -d --name aerospike -p 3000-3002:3000-3002 ${{ inputs.docker-image }}:latest

    - name: Wait for database to be ready
      # Should be ready after 3 seconds
      run: sleep 3

    - name: Run tests
      run: python -m pytest ./new_tests
      working-directory: test
