on:
  workflow_call:
    inputs:
      runner-os:
        required: true
        type: string
      # For downloading the correct wheel from upstream jobs
      python-version:
        required: true
        type: string
      server-tag:
        required: true
        type: string
      run-integration-tests:
        type: boolean
        required: false
        default: true
        description: 'If false, only run import test'
      test-ce:
        type: boolean
        required: false
        default: false
        description: 'If false, run EE server'
      test-file:
        required: false
        type: string
        default: ''
      test-metadata:
        required: false
        type: string
    secrets:
      MAC_M1_SELF_HOSTED_RUNNER_PW:
        required: false

jobs:
  test-wheel:
    runs-on: ${{ inputs.runner-os }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Get platform tag of wheel to download
      run: |
        os=$(uname -s)
        arch=$(uname -m)
        if [[ $os =~ Darwin* ]]; then
          PLATFORM_TAG_GLOB_PATTERN="*macosx_$arch*"
        elif [[ $os =~ CYGWIN* || $os =~ MINGW* ]]; then
          PLATFORM_TAG_GLOB_PATTERN=*win_amd64*
        elif [[ $os =~ Linux* ]]; then
          PLATFORM_TAG_GLOB_PATTERN="*linux*$arch*"
        fi
        echo "PLATFORM_TAG_GLOB_PATTERN=$PLATFORM_TAG_GLOB_PATTERN" >> $GITHUB_ENV
      shell: bash

    - name: Create status check message
      run: |
        echo STATUS_CHECK_MESSAGE="Test wheel (${{ inputs.python-version }}-$PLATFORM_TAG_GLOB_PATTERN)" >> $GITHUB_ENV
      shell: bash

    - name: Show job status for commit
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
      with:
        sha: ${{ github.sha }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - run: echo GH_ARTIFACT_PATTERN_FOR_WHEEL=${{ vars.GH_ARTIFACT_NAME_PREFIX_FOR_BUILDS }}-${{ inputs.python-version }}-*linux*x86_64 >> $GITHUB_ENV

    - if: ${{ inputs.test-metadata == 'sanitizer' }}
      run: echo GH_ARTIFACT_PATTERN_FOR_WHEEL=$GH_ARTIFACT_PATTERN_FOR_WHEEL-sanitizer >> $GITHUB_ENV

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: ${{ env.GH_ARTIFACT_PATTERN_FOR_WHEEL }}
        path: ./

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install wheel
      run: pip install *.whl
      shell: bash

    - if: ${{ inputs.run-integration-tests }}
      run: pip install -r requirements.txt
      working-directory: test
      shell: bash

    # Need to be able to save Docker Hub credentials to keychain
    # Unable to do this via the ansible script for self hosted mac m1 runners
    - if: ${{ inputs.run-integration-tests && env.PLATFORM_TAG_GLOB_PATTERN == 'macosx_arm64' }}
      run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
      shell: bash

    - name: 'macOS x86: Setup Docker using colima for testing'
      if: ${{ inputs.run-integration-tests && env.PLATFORM_TAG_GLOB_PATTERN == 'macosx_x86_64' }}
      uses: ./.github/actions/setup-docker-on-macos

    - if: ${{ inputs.run-integration-tests && inputs.test-ce }}
      name: Run CE server
      run: |
        docker run -d --name aerospike -p 3000-3002:3000-3002 -e DEFAULT_TTL=2592000 aerospike/aerospike-server:${{ inputs.server-tag }}
        cp config.conf.template config.conf
      working-directory: test

    - if: ${{ inputs.run-integration-tests && inputs.test-ce }}
      uses: ./.github/actions/wait-for-ce-server-to-start
      with:
        container-name: aerospike

    - if: ${{ inputs.run-integration-tests && inputs.test-ce == false }}
      uses: ./.github/actions/run-ee-server
      with:
        oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
        oidc-audience: ${{ vars.OIDC_AUDIENCE }}
        server-tag: ${{ inputs.server-tag }}
        where-is-client-connecting-from: ${{ env.PLATFORM_TAG_GLOB_PATTERN == 'win_amd64' && 'remote-connection' || 'docker-host' }}

    # We can already detect leaks using valgrind
    # halt_on_error must be enabled, or else this job won't fail if a memory error occurs
    - if: ${{ inputs.test-metadata == 'sanitizer' }}
      run: |
        echo ASAN_OPTIONS='detect_stack_use_after_return=1:detect_leaks=0' >> $GITHUB_ENV
        echo LD_PRELOAD=$(gcc --print-file-name=libasan.so) >> $GITHUB_ENV

    - if: ${{ inputs.test-metadata == 'dont_validate_keys' }}
      run: crudini --existing=param --set config.conf input-validation validate_keys false
      working-directory: test

    # -s: we want to check that the test_create_pki_user test case passes or raises an exception as expected
    # There's no way to tell unless we see the logs
    - if: ${{ inputs.run-integration-tests }}
      run: python3 -m pytest -vvs --full-trace new_tests/${{ inputs.test-file }} -W error::pytest.PytestUnraisableExceptionWarning -W error::DeprecationWarning
      working-directory: test
      shell: bash

    - if: ${{ inputs.run-integration-tests == false }}
      run: python3 -c "import aerospike"
      shell: bash

    - name: Show server logs to debug test results
      if: ${{ always() && inputs.run-integration-tests }}
      run: docker logs aerospike
      shell: bash

    - name: Show job status for commit
      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        sha: ${{ github.sha }}
        status: ${{ job.status }}
        context: ${{ env.STATUS_CHECK_MESSAGE }}
