name: Publish JFrog build to PyPI
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Build version
        required: true
      use-test-pypi:
        type: boolean
        description: 'DEBUG: upload to test.pypi.org?'
        required: true
        default: false

jobs:
  publish-jfrog-build-to-pypi:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: step-security/setup-jfrog-cli@3054b554c0fb4915b3d58847fb7730c593dbb934 # v5.0.0
      env:
        JF_URL: ${{ secrets.JFROG_PLATFORM_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

    - name: Download JFrog build
      run: jf rt dl --build python-client/${{ inputs.version }} ${{ vars.JFROG_REPO_NAME }}

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
      with:
        # This is the directory jf downloads the artifacts to
        packages-dir: aerospike/${{ inputs.version }}/artifacts
        repository-url: ${{ inputs.use-test-pypi && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
        password: ${{ inputs.use-test-pypi && secrets.TEST_PYPI_API_TOKEN || secrets.PYPI_API_TOKEN }}
