name: Upload to JFrog

on:
  workflow_call:
    inputs:
      dry-run:
        required: false
        default: false
        type: boolean
        description: "Don't upload to jfrog"
      version:
        type: string
        required: false
      jfrog-repo-name:
        type: string
        required: false
        default: ${{ vars.JFROG_REPO_NAME }}
    secrets:
      JFROG_PLATFORM_URL:
        required: true
      JFROG_ACCESS_TOKEN:
        required: true

jobs:
  upload-to-jfrog:
    name: Upload artifacts to JFrog
    runs-on: ubuntu-22.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: 'build-artifacts*'
        merge-multiple: true
        path: artifacts

    - name: Set up JFrog credentials
      uses: step-security/setup-jfrog-cli@3054b554c0fb4915b3d58847fb7730c593dbb934 # v5.0.0
      env:
        JF_URL: ${{ secrets.JFROG_PLATFORM_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

    - if: ${{ inputs.dry-run }}
      run: echo "DRY_RUN_FLAG=--dry-run" >> $GITHUB_ENV

    - name: Upload manylinux builds from arbitrary branches to JFrog generic repo
      if: ${{ inputs.jfrog-repo-name == vars.JFROG_GENERIC_REPO_NAME }}
      run: jf rt upload $DRY_RUN_FLAG "*manylinux*" ${{ vars.JFROG_GENERIC_REPO_NAME }}/${{ github.ref_name }}/
      working-directory: artifacts
